import { Post, S } from './types';
const C = `${S}/create`;
const c = 'deep-emotional';

export const deepEmotional: Post[] = [
{text:`I think about this a lot:\n\nWe take thousands of photos. We save screenshots. We hoard memories digitally. But how often do we actually CAPTURE what someone means to us?\n\nNot a photo of them — that shows what they LOOK like.\nNot a text — that fades in a thread.\n\nBut something that captures how they make you FEEL? What they've DONE for you? Why they MATTER?\n\nA custom song does that. It's the only gift format that captures emotion itself. Not a moment. Not a face. The actual feeling of loving someone.\n\nAnd unlike a photo that sits in your camera roll... a song gets played. Over and over.\n\n#love #customsong #memories #emotional #gifts #feelings`,link:C,category:c},

{text:`The people who love us the most are usually the ones who hear "thank you" the least.\n\nYour mom who called every Sunday even when you were "too busy."\nYour dad who drove 6 hours to help you move — again.\nYour partner who held everything together while you fell apart.\nYour friend who showed up without being asked.\n\nThey did it because they love you. Not because they expected recognition.\n\nBut imagine if you gave them a song that said: "I noticed. I remember. And this is what you mean to me."\n\nThe people who expect nothing deserve everything.\n\n#grateful #thankful #customsong #appreciation #familylove #lovesong`,link:C,category:c},

{text:`A love story doesn't need to be dramatic to be beautiful.\n\nIt doesn't need a grand gesture or a movie moment. Some of the best love stories are quiet:\n\nThe way they always make your coffee without asking.\nHow they reach for your hand in the car.\nThe "drive safe" text you get every single morning.\nComing home to them after the worst day and instantly feeling okay.\n\nThat quiet, consistent, showing-up-every-day love? It's not boring. It's RARE.\n\nAnd it deserves to be celebrated. Out loud. In music.\n\nA custom song about the quiet love is the most powerful one we make.\n\n#quietlove #relationships #lovesong #customsong #realromance #everydaylove`,link:C,category:c},

{text:`Here's something nobody prepares you for:\n\nThe moment you realize your parents are getting older.\n\nThe grey hair. The slower steps. The repeated stories you used to roll your eyes at but now listen to like they're running out.\n\nYou start thinking: "Do they know? Do they know how much they mean to me? Did I say it enough?"\n\nHere's the truth: it's never too late and it's never too much.\n\nA custom song for your parent — about the childhood they gave you, the sacrifices they made, the love that shaped who you are — that's not just a gift.\n\nIt's documentation. Proof. Something they can hold onto and play whenever they need to remember they did it right.\n\nDon't wait.\n\n#parents #familylove #giftformom #giftfordad #customsong #whiletheyrehere`,link:`${S}/custom-song-for-mom`,category:c},

{text:`Lost someone you can't stop thinking about?\n\nGrief doesn't follow a timeline. It shows up randomly — in a smell, a song on the radio, a dream where they're still here.\n\nA custom memorial song doesn't make the grief go away. But it gives you somewhere to put it.\n\n3 minutes where you can remember them on purpose. Their laugh. Their sayings. The life they lived. The hole they left.\n\nSome people play it every day. Some only on birthdays and anniversaries. But everyone says the same thing: "It helps. It helps to hear their story out loud."\n\nIf you're carrying someone with you who's no longer here — a song keeps them close in a way nothing else can.\n\n#grief #loss #memorial #inmemory #customsong #healingjourney #grieving`,link:`${S}/memorial-tribute-song`,category:c},

{text:`Marriages get comfortable. That's not a bad thing — it means you're safe. But sometimes "comfortable" starts to feel like "invisible."\n\nShe's still here. Still making it work. Still loving you in a hundred quiet ways you've stopped noticing.\n\nWhen's the last time she felt CHOSEN? Not out of habit. Not because of the kids. But because you looked at her and thought: "I'd pick you again. Every time. No question."\n\nA custom song that says THAT? About the specific reasons you'd choose her all over again?\n\nThat's not just a gift. That's a reset. A reminder. A declaration that the love didn't fade — it deepened.\n\nShe needs to hear it.\n\n$79.\n\n#marriage #wife #husbandgoals #loveyourwife #customsong #marriedlife #chooseyou`,link:`${S}/custom-song-for-wife`,category:c},

{text:`To the person reading this who's been putting off telling someone how they feel:\n\nYou keep thinking there will be a "right time." A perfect moment. A day when the words will just come naturally.\n\nBut life doesn't guarantee perfect moments. It guarantees TODAY.\n\nIf someone matters to you — a partner, a parent, a friend, anyone — don't wait for the perfect time. Make the time. Say it. Or if saying it feels impossible... sing it.\n\nA custom song says everything your voice can't. And once they hear it, they'll never have to wonder how you feel again.\n\nDon't wait.\n\n#tellthemtoday #love #customsong #dontwaittosayiloveyou #life #nomorewaiting`,link:C,category:c},

{text:`There's a reason people save voicemails from loved ones who've passed.\n\nIt's not about the words. It's about hearing their PRESENCE. Feeling close to them through sound.\n\nA custom song for a living loved one does the same thing — but on purpose. It captures their essence, their story, their impact on your life. In music that lasts forever.\n\nAnd a memorial song for someone gone? It gives you a way to hear their story whenever you need it. To feel close to them through sound, just like a voicemail — but intentional. Complete. Beautiful.\n\nWhether they're here or not — a song keeps people close.\n\n$79.\n\n#voicemails #memories #customsong #memorial #lovesong #keepthemclose`,link:C,category:c},
];
