import { Post, S } from './types';
const C = `${S}/create`;
const c = 'emotional';
export const emotional: Post[] = [
{text:`Some gifts are forgotten in a week. A custom song? They'll listen to it for the rest of their life.\n\nTurn your love story into a song they'll never forget.`,link:C,category:c},
{text:`What if you could bottle up every "I love you," every inside joke, every quiet moment — and turn it into a song?\n\nThat's exactly what we do.`,link:C,category:c},
{text:`A personalized song says what a card never could.\n\nYour memories. Your words. Your love. Set to music.`,link:C,category:c},
{text:`The best gift isn't something they can hold — it's something they can feel.\n\nGive them a song made just for them.`,link:C,category:c},
{text:`Imagine their face when they hear their name in a song for the first time.\n\nThat moment? Priceless.`,link:C,category:c},
{text:`Not all love letters are written on paper.\n\nSome are sung. Yours could be next.`,link:C,category:c},
{text:`You don't need to be a songwriter to give someone a song.\n\nJust tell us your story. We'll handle the rest.`,link:C,category:c},
{text:`They gave you butterflies. You can give them goosebumps.\n\nA custom song captures what words alone can't.`,link:C,category:c},
{text:`"I cried the first time I heard it."\n\nThat's what our customers say. A personalized song hits different.`,link:`${S}/reviews`,category:c},
{text:`Flowers die. Chocolate gets eaten. A custom song lives forever.\n\nGive them a gift that never fades.`,link:C,category:c},
{text:`What if the most meaningful gift you ever give costs less than dinner for two?\n\nCustom songs starting at $79. Memories? Priceless.`,link:C,category:c},
{text:`There's a song inside your love story waiting to be heard.\n\nLet us find it for you.`,link:C,category:c},
{text:`They don't need another gift card. They need to know how you feel.\n\nSay it with a song.`,link:C,category:c},
{text:`The first time they press play, everything stops.\n\nA personalized song is a moment frozen in time.`,link:C,category:c},
{text:`You remember the little things. The way they laugh. How they say your name.\n\nWe turn those details into music.`,link:C,category:c},
{text:`What would you say to someone you love if you had 3 minutes and a melody?\n\nWe help you say it.`,link:C,category:c},
{text:`"I didn't think I'd cry. I was wrong."\n\nA custom song reaches places no other gift can.`,link:C,category:c},
{text:`Some people write poems. Some write letters. You? You're about to give them a whole song.\n\nStart creating yours today.`,link:C,category:c},
{text:`The most personal gift in the world isn't wrapped in paper.\n\nIt's wrapped in melody.`,link:C,category:c},
{text:`You know that feeling when a song comes on and takes you right back to a moment?\n\nImagine giving someone THAT feeling — on purpose.`,link:C,category:c},
{text:`Every love story has a soundtrack. Most people just haven't written theirs yet.\n\nWe can help with that.`,link:C,category:c},
{text:`A handwritten note is sweet. A custom song? That's next level.\n\nGive them something they'll replay for years.`,link:C,category:c},
{text:`The look on their face. The tears they try to hold back. The "how did you do this?"\n\nThat's the SongGift moment.`,link:C,category:c},
{text:`You've thought about what to say a thousand times.\n\nLet a melody carry those words for you.`,link:C,category:c},
{text:`Music is the language of emotion.\n\nA personalized song speaks fluently in love.`,link:C,category:c},
{text:`Your story is one of a kind. Your gift should be too.\n\nA custom song — written just for the person you love.`,link:C,category:c},
{text:`Close your eyes. Think of them.\n\nNow imagine giving them a song that captures exactly what they mean to you.`,link:C,category:c},
{text:`Gifts come and go. But a song about your love? That stays in their heart.\n\nForever.`,link:C,category:c},
{text:`They'll listen to it in the car. In bed. On repeat.\n\nA personalized song becomes part of their life.`,link:C,category:c},
{text:`You've been together through everything.\n\nA custom song celebrates the journey — every high, every quiet Tuesday, every "I'm here."`,link:C,category:c},
{text:`It's not just a song. It's every memory, every feeling, every "I love you" — set to music.\n\nCreate yours today.`,link:C,category:c},
{text:`A gift that makes them cry happy tears?\n\nYep. We do that.`,link:C,category:c},
{text:`The difference between a good gift and an unforgettable one?\n\nA personalized song.`,link:C,category:c},
{text:`You don't need a special occasion to tell someone they matter.\n\nA custom song says it any day of the year.`,link:C,category:c},
{text:`Imagine playing a song for them and watching the realization hit…\n\n"Wait… this is about US?"\n\nYes. Yes it is.`,link:C,category:c},
{text:`3 minutes. That's all it takes to make someone feel like the most loved person on earth.\n\nOne song. Their story. Your love.`,link:C,category:c},
{text:`We take your story and turn it into something they can feel.\n\nEvery note. Every lyric. Made for them.`,link:C,category:c},
{text:`"I've listened to it 47 times and I still cry."\n\nThat's the power of a personalized song.`,link:C,category:c},
{text:`Your love doesn't fit inside a greeting card.\n\nIt fits inside a song.`,link:C,category:c},
{text:`Think about the best gift you've ever received.\n\nNow imagine topping it.\n\nA custom song does that.`,link:C,category:c},
{text:`It's not about perfect pitch. It's about perfect timing.\n\nGive them a song that says "I love you" at exactly the right moment.`,link:C,category:c},
{text:`Your relationship has a story.\n\nIt deserves a song.`,link:C,category:c},
{text:`Stop scrolling for gift ideas.\n\nThe answer is a custom song. You're welcome.`,link:C,category:c},
{text:`They'll share it with their friends. Their family. Their group chat.\n\n"Listen to what they made for me."\n\nA custom song becomes their favorite brag.`,link:C,category:c},
{text:`A $79 custom song > a $200 gift they'll forget about.\n\nInvest in something that matters.`,link:C,category:c},
{text:`We don't sell songs. We sell moments.\n\nThe kind you'll both remember forever.`,link:C,category:c},
{text:`Your love is loud. Your gift should be too.\n\nTurn up the volume on your feelings with a custom song.`,link:C,category:c},
{text:`Some things in life you can't put a price on.\n\nSeeing their face when they hear their custom song is one of them.`,link:C,category:c},
{text:`You know those movies where the couple has "their song"?\n\nYou can actually make that real.`,link:C,category:c},
{text:`A custom song doesn't just sit on a shelf.\n\nIt plays in the car. At dinner. In the shower. On loop.\n\nIt becomes part of their world.`,link:C,category:c},
{text:`Want to make someone feel like the main character?\n\nGive them a song that's literally about them.`,link:C,category:c},
{text:`Every time they hear it, they'll think of you.\n\nA custom song is a gift that keeps giving.`,link:C,category:c},
{text:`Your feelings deserve more than a text message.\n\nThey deserve a whole song.`,link:C,category:c},
{text:`"I didn't know a gift could make me feel that loved."\n\nNow you do.`,link:C,category:c},
{text:`The world is noisy. But a personalized song? That cuts through everything and goes straight to the heart.`,link:C,category:c},
{text:`Not sure how to say what you feel?\n\nLet us write it, sing it, and deliver it. That's what we do.`,link:C,category:c},
{text:`One song. One story. One person who'll never forget it.\n\nCreate theirs now.`,link:C,category:c},
{text:`A custom song is proof that the best things in life aren't things.\n\nThey're feelings. Set to music.`,link:C,category:c},
{text:`Sometimes words aren't enough.\n\nBut words + melody + your real story? That's everything.`,link:C,category:c},
{text:`They supported you at your worst. Celebrated you at your best.\n\nReturn the love with a song they'll treasure forever.`,link:C,category:c},
{text:`Imagine them putting in their earbuds, pressing play… and realizing someone loved them enough to write a whole song about it.\n\nBe that someone.`,link:C,category:c},
{text:`A custom song isn't just heard.\n\nIt's felt. Deep in the chest. In the way your eyes water without permission.`,link:C,category:c},
{text:`You've probably spent hours looking for the perfect gift.\n\nStop looking. A custom song IS the perfect gift.`,link:C,category:c},
{text:`Love is messy. Beautiful. Complicated. Simple. All at once.\n\nA personalized song captures every shade of it.`,link:C,category:c},
{text:`Gift-giving anxiety? Gone.\n\nA custom song = guaranteed tears of joy. Every. Single. Time.`,link:C,category:c},
{text:`What's more romantic than a mixtape?\n\nA whole song. Written about YOUR love story.`,link:C,category:c},
{text:`When they ask "what's this?" and you press play…\n\nThat silence before the tears? That's everything.`,link:C,category:c},
{text:`We've turned first dates, late-night drives, and kitchen dances into songs.\n\nWhat's your moment?`,link:C,category:c},
{text:`A personalized song doesn't expire. It doesn't break. It doesn't need batteries.\n\nIt just keeps making them feel loved.`,link:C,category:c},
{text:`You told them "I love you" a hundred times.\n\nNow let a song say it in a way they've never heard before.`,link:C,category:c},
{text:`What makes someone feel truly seen?\n\nA gift that says "I know you. I remember. You matter."\n\nThat's a custom song.`,link:C,category:c},
{text:`Your love story is already beautiful.\n\nWe just give it a melody.`,link:C,category:c},
{text:`They'll play it when they miss you. When they're happy. When they just want to feel something.\n\nA custom song is always there.`,link:C,category:c},
{text:`In a world of mass-produced everything…\n\nA personalized song is refreshingly, beautifully, impossibly personal.`,link:C,category:c},
{text:`Some gifts say "I was thinking of you."\n\nA custom song says "I was thinking of every moment with you."`,link:C,category:c},
{text:`It starts with your story.\n\nIt ends with their tears.\n\nIn between? Pure magic. That's SongGift.`,link:C,category:c},
{text:`One day they'll tell the story of the greatest gift they ever received.\n\nMake sure it's a song from you.`,link:C,category:c},
{text:`Everyone says "I love you."\n\nBut not everyone writes a whole song about it.`,link:C,category:c},
{text:`Life is short. Love is long.\n\nCapture it in a song before it becomes a memory.`,link:C,category:c},
{text:`You've given jewelry. Flowers. Vacations.\n\nBut have you given them their own song?\n\nThat's the one that'll stay.`,link:C,category:c},
{text:`A personalized song is the ultimate "I see you and I love every part of you" gift.\n\nNo assembly required.`,link:C,category:c},
{text:`They don't need more stuff.\n\nThey need to feel how much they mean to you.\n\nA song does that.`,link:C,category:c},
{text:`Somewhere between the first verse and the chorus, they'll realize no one has ever made them feel this special.\n\nBe the one who does.`,link:C,category:c},
{text:`Music doesn't just play in your ears.\n\nIt plays in your soul.\n\nGive them a song that touches theirs.`,link:C,category:c},
{text:`The gift they'll talk about at every dinner party for the next decade?\n\nA personalized song. Guaranteed.`,link:C,category:c},
{text:`You can say "I appreciate you" or you can SHOW it — with lyrics, a melody, and a voice singing their story.\n\nWhich one hits harder?`,link:C,category:c},
{text:`We've made grown men cry. Grandmas dance. Teenagers speechless.\n\nAll from one personalized song.`,link:C,category:c},
{text:`A custom song isn't a gift.\n\nIt's an experience. A moment. A feeling they carry with them everywhere they go.`,link:C,category:c},
{text:`Your heart knows what to say.\n\nLet us put it to music.`,link:C,category:c},
{text:`Regret not getting the perfect gift? Not this time.\n\nA custom song is always the right choice.`,link:C,category:c},
{text:`What if I told you that for $79, you could make someone feel more loved than they've ever felt?\n\nBelieve it. We do it every day.`,link:C,category:c},
{text:`Some moments deserve more than a photo.\n\nThey deserve their own song.`,link:C,category:c},
{text:`Think about the person who changed your life.\n\nNow think about giving them a song that changes theirs.\n\nThat's what we do.`,link:C,category:c},
{text:`When they ask "Why did you do this for me?" — you won't need to answer.\n\nThe song already did.`,link:C,category:c},
{text:`We create songs people press repeat on.\n\nBecause when it's about your love story, once is never enough.`,link:C,category:c},
{text:`The most meaningful gift doesn't come from a store.\n\nIt comes from your story, your heart, and your memories. We just add the music.`,link:C,category:c},
];
