import { Post, S } from './types';
const C = `${S}/create`;
const c = 'emotional';
const P = `${S}/playlist`;
export const emotional2: Post[] = [
{text:`A song isn't just notes on a page.\n\nIt's the sound of someone being truly loved.`,link:C,category:c},
{text:`Your memories are fading. But a custom song captures them in a way that feels alive. Every single time.`,link:C,category:c},
{text:`The best surprise isn't a trip or a party.\n\nIt's pressing play and watching someone realize… this song is about THEM.`,link:C,category:c},
{text:`Three minutes. That's all a song needs to change someone's entire day.\n\nOr their entire life.`,link:C,category:c},
{text:`A custom song is the difference between a gift they keep and a gift they treasure.`,link:C,category:c},
{text:`They'll whisper "how did you do this?" through tears.\n\nAnd you'll just smile.\n\nBecause you know.`,link:C,category:c},
{text:`No algorithm picked this song for you.\n\nNo playlist suggested it.\n\nSomeone who loves you had it made.\n\nThat's a custom song.`,link:C,category:c},
{text:`You know the feeling when a song perfectly describes your life?\n\nNow imagine that song was MADE for your life.`,link:C,category:c},
{text:`Love doesn't come in standard sizes.\n\nSo why give a standard gift?\n\nA custom song fits perfectly. Every time.`,link:C,category:c},
{text:`They won't just hear the song.\n\nThey'll feel the song.\n\nIn their chest. In their eyes. In the silence after it ends.`,link:C,category:c},
{text:`Every couple has a song. But most didn't choose it.\n\nWith a custom song, you do. And it's about YOU.`,link:C,category:c},
{text:`The internet is full of noise.\n\nA custom song cuts through it all with three words:\n\nThis is YOURS.`,link:C,category:c},
{text:`You found the perfect person.\n\nNow find the perfect gift.\n\nA custom song. Obviously.`,link:C,category:c},
{text:`It takes courage to tell someone how you feel.\n\nA custom song gives that courage a melody.`,link:C,category:c},
{text:`They supported you when things fell apart.\n\nA custom song says "I'll never forget what you did."`,link:C,category:c},
{text:`Not every "I love you" needs to be spoken.\n\nSome of the most powerful ones are sung.`,link:C,category:c},
{text:`A photo is a moment captured.\n\nA custom song is an emotion captured.\n\nWhich one gives you goosebumps?`,link:C,category:c},
{text:`They scroll past a hundred ads a day.\n\nBut they'll never scroll past a song made about them.`,link:C,category:c},
{text:`Love languages: words, time, gifts, touch, service.\n\nA custom song speaks ALL FIVE at once.`,link:C,category:c},
{text:`A custom song doesn't need wrapping paper.\n\nIt unwraps feelings you didn't know you had.`,link:C,category:c},
{text:`You could send a message.\n\nOr you could send a SONG.\n\nOne gets a heart emoji. The other gets real tears.`,link:C,category:c},
{text:`The playlist of their life just got a new #1.\n\nA custom song about your love.`,link:C,category:c},
{text:`Some gifts are nice.\n\nA custom song is necessary.\n\nBecause some feelings NEED to be heard.`,link:C,category:c},
{text:`Year one: flowers.\nYear five: jewelry.\nYear ten: a custom song.\n\nThe gift that levels up your love.`,link:C,category:c},
{text:`Every lyric is a memory.\nEvery note is an emotion.\nEvery song is a love letter.\n\nCreate yours.`,link:C,category:c},
{text:`They don't want perfection.\n\nThey want to be known. Seen. Celebrated.\n\nA custom song does all three.`,link:C,category:c},
{text:`We believe every love story deserves a soundtrack.\n\nWhat's stopping you from creating yours?`,link:C,category:c},
{text:`A custom song is a bookmark in the story of your life.\n\nEvery time you play it, you go back to that moment.`,link:C,category:c},
{text:`They've given you more than you can count.\n\nGive them something you can't put a number on — a personalized song.`,link:C,category:c},
{text:`A text says "I'm thinking of you."\n\nA custom song says "I'm thinking of EVERYTHING about you."`,link:C,category:c},
{text:`The world moves fast.\n\nA custom song makes it stop — just long enough to feel everything.`,link:C,category:c},
{text:`We don't just write songs.\n\nWe capture moments that would otherwise be lost to time.`,link:C,category:c},
{text:`You remember the way they looked at you that one time.\n\nA custom song turns that look into a feeling you can replay forever.`,link:C,category:c},
{text:`They've heard every love song on the radio.\n\nBut they've never heard one about THEM.\n\nUntil now.`,link:C,category:c},
{text:`Some gifts gather dust.\n\nA custom song gathers meaning — more and more, every time it plays.`,link:C,category:c},
{text:`The moment the song starts, time slows down.\n\nTheir eyes widen. Their lip trembles.\n\nThat's the magic of a custom song.`,link:C,category:c},
{text:`You fell in love for a reason.\n\nA custom song is the reason — beautifully arranged.`,link:C,category:c},
{text:`A diamond says "I love you."\n\nA custom song says "Let me tell you exactly how much, and why, and when it started."`,link:C,category:c},
{text:`The most listened-to song on their phone?\n\nSoon, it'll be the custom one you gave them.`,link:C,category:c},
{text:`People save texts. They save photos. They save voicemails.\n\nBut a custom song? They save that in their SOUL.`,link:C,category:c},
{text:`It's 2am. They can't sleep. They put in their earbuds.\n\nThe song you made for them starts playing.\n\nAnd suddenly, everything's okay.`,link:C,category:c},
{text:`Creating a custom song is easy.\n\nForgetting how it made them feel? Impossible.`,link:C,category:c},
{text:`Every great love story has a moment.\n\nEvery great moment deserves a melody.\n\nWe make both.`,link:C,category:c},
{text:`It's not about the money.\n\nIt's about the message.\n\nA $79 custom song carries a message worth millions.`,link:C,category:c},
{text:`They'll hear their name and freeze.\n\nThen the memories start flooding back.\n\nThat's a custom song doing its thing.`,link:C,category:c},
{text:`Some people pray. Some people journal.\n\nSome people express love through a custom song.\n\nAll of them are healing.`,link:C,category:c},
{text:`A custom song doesn't ask for anything in return.\n\nIt just gives. Again. And again. And again.`,link:C,category:c},
{text:`When words fail, music speaks.\n\nWhen music is personal? It SCREAMS love.`,link:C,category:c},
{text:`You're not buying a product.\n\nYou're creating a moment.\n\nA moment that lasts forever. That's SongGift.`,link:C,category:c},
{text:`The first listen is the best.\n\nBut the hundredth listen? That's when it becomes part of their identity.`,link:C,category:c},
{text:`If love had a sound, it would be a custom song.\n\nSpecific. Personal. Irreplaceable.`,link:C,category:c},
{text:`They'll add it to every playlist.\n\nPlay it at every gathering.\n\nTell everyone who made it happen.\n\nThat's you.`,link:C,category:c},
{text:`Tired of generic gifts?\n\nA custom song is the opposite of generic.\n\nIt's aggressively, beautifully personal.`,link:C,category:c},
{text:`The silence after the song ends is the loudest part.\n\nBecause that's when they realize how deeply they're loved.`,link:C,category:c},
{text:`We've seen videos of people hearing their custom song.\n\nEvery single one makes US cry too.\n\nThat's how we know we're doing it right.`,link:C,category:c},
{text:`A custom song = a time machine.\n\nEvery listen takes them back to the moment. The feeling. The love.`,link:C,category:c},
{text:`You don't need a reason to give someone a custom song.\n\n"Because I love you" is reason enough.`,link:C,category:c},
{text:`The gift they never asked for — because they never imagined it existed.\n\nA custom song. Theirs. Forever.`,link:C,category:c},
{text:`Your love story is already incredible.\n\nAll it needs is a soundtrack.\n\nLet us write it.`,link:C,category:c},
{text:`They say the best things in life are free.\n\nBut for $79, a custom song comes pretty close.`,link:C,category:c},
{text:`A custom song isn't a trend.\n\nIt's a tradition in the making.\n\nThe gift your family will talk about for generations.`,link:C,category:c},
{text:`Music has the power to heal.\n\nA personalized song has the power to make someone feel completely, unconditionally loved.`,link:C,category:c},
{text:`Before you settle for another "safe" gift…\n\nAsk yourself: what if I gave them something they'd never forget?\n\nThat's a custom song.`,link:C,category:c},
{text:`Everyone deserves to feel like the most important person in the room.\n\nA custom song makes that happen — even when you're not in the room.`,link:C,category:c},
{text:`Your love is the lyrics.\n\nWe just add the melody.`,link:C,category:c},
{text:`A custom song doesn't shout.\n\nIt whispers — right into their heart.`,link:C,category:c},
{text:`The most meaningful things in life can't be Googled.\n\nThey have to be felt.\n\nLike a custom song about your story.`,link:C,category:c},
{text:`Imagine them in their car, windows down, YOUR song playing.\n\nSmiling. Because someone loved them enough to create it.`,link:C,category:c},
{text:`A custom song is proof.\n\nProof that someone took the time. Made the effort. Felt the love.\n\nAnd turned it into music.`,link:C,category:c},
{text:`Stop overthinking the perfect gift.\n\nIt's a custom song. It was always a custom song.`,link:C,category:c},
{text:`Your love story has chapters.\n\nA custom song is the one they'll dog-ear and return to again and again.`,link:C,category:c},
{text:`We turn "I don't know what to get them" into "I can't believe I didn't do this sooner."\n\nCustom songs. Starting at $79.`,link:C,category:c},
{text:`It's just a song.\n\nUntil it's about YOU.\n\nThen it's everything.`,link:C,category:c},
{text:`There's something powerful about hearing your name in a song.\n\nIt makes you feel chosen. Seen. Loved.\n\nGive them that feeling.`,link:C,category:c},
{text:`They'll text you at 2am: "I just listened to the song again."\n\nThat text? Worth more than any "thank you."`,link:C,category:c},
{text:`A custom song is the gift that ages like fine wine.\n\nBetter every listen. More meaningful every year.`,link:C,category:c},
{text:`Spotify has 100 million songs.\n\nNone of them are about your story.\n\nUntil you create one with us.`,link:C,category:c},
{text:`Love isn't always loud.\n\nSometimes it's a quiet song, playing in the background of someone's favorite moment.`,link:C,category:c},
{text:`The gift they'll mention at your wedding. At family dinners. At your 50th anniversary.\n\nIt starts with pressing "order."`,link:C,category:c},
{text:`We asked our customers: "What was their reaction?"\n\nThe #1 answer: "They cried before the first chorus."\n\nYeah. It's that good.`,link:C,category:c},
{text:`Some moments are too big for words.\n\nThey need a melody. A verse. A bridge.\n\nThey need a custom song.`,link:C,category:c},
{text:`A custom song isn't a purchase.\n\nIt's a declaration of love.\n\nWrapped in music.`,link:C,category:c},
{text:`You've been meaning to tell them how you feel.\n\nStop meaning to. Start singing.\n\nCreate their custom song today.`,link:C,category:c},
{text:`What if the greatest love letter ever written... was actually a song?\n\nLet's find out. Together.`,link:C,category:c},
{text:`A handshake says "nice to meet you."\n\nA custom song says "you changed my life."\n\nKnow the difference.`,link:C,category:c},
{text:`From "what should I get them?" to "this is the best gift ever."\n\nThe custom song pipeline.`,link:C,category:c},
{text:`It costs $79.\n\nBut the look on their face?\n\nAbsolutely priceless.`,link:C,category:c},
{text:`A custom song is what happens when love meets creativity meets technology.\n\nAnd the result? Magic.`,link:C,category:c},
{text:`They'll listen to it when they're happy.\n\nWhen they're sad.\n\nWhen they need to remember they're loved.\n\nAlways.`,link:C,category:c},
{text:`Not all heroes wear capes.\n\nSome just order custom songs for the people they love.`,link:C,category:c},
{text:`You could say "I love you" or you could PLAY "I love you."\n\nOne is words. The other is a custom song.\n\nYou know which hits harder.`,link:C,category:c},
{text:`Custom songs: the gift that turns "I didn't know what to get you" into "this is the greatest gift I've ever received."`,link:C,category:c},
{text:`A custom song is a hug you can hear.\n\nAnytime. Anywhere. Forever.`,link:C,category:c},
{text:`Somewhere right now, someone is hearing their custom song for the first time.\n\nAnd they're ugly crying.\n\nDo you want that to be YOUR person?`,link:C,category:c},
{text:`If you've scrolled this far, you're already thinking about who deserves a custom song.\n\nTrust that feeling. Create it now.`,link:C,category:c},
{text:`Last chance to give the gift of a lifetime.\n\nJust kidding. You can order anytime.\n\nBut seriously — don't wait. They deserve it now.`,link:C,category:c},
];
