import { Post, S } from './types';
const C = `${S}/create`;
const c = 'emotional';
export const emotional3: Post[] = [
{text:`If your heart could talk, what would it say?\n\nA custom song gives it a voice.`,link:C,category:c},
{text:`The greatest gift isn't measured in dollars.\n\nIt's measured in how long someone holds their breath before crying.\n\nCustom songs win.`,link:C,category:c},
{text:`They looked at you once and the whole world changed.\n\nA custom song remembers that moment.`,link:C,category:c},
{text:`Life is loud.\n\nA custom song is a quiet promise: "You are loved."`,link:C,category:c},
{text:`When was the last time you surprised someone into complete silence?\n\nA custom song does that.`,link:C,category:c},
{text:`A gift says "I care."\n\nA custom song says "I care enough to put our story into music."`,link:C,category:c},
{text:`They'll hear the opening notes and stop everything.\n\nBy the chorus, they're a puddle.\n\nBy the end? They're pressing replay.`,link:C,category:c},
{text:`Your memories are priceless.\n\nA custom song gives them a permanent address.`,link:C,category:c},
{text:`If music is the universal language, then a custom song is the most personal dialect.`,link:C,category:c},
{text:`You showed up when it mattered.\n\nA custom song says "I'll keep showing up. In every lyric. Every note."`,link:C,category:c},
{text:`A sunset is beautiful but it fades.\n\nA custom song is beautiful and it STAYS.`,link:C,category:c},
{text:`You've seen each other at 3am with messy hair and messy hearts.\n\nThat's real love.\n\nThat deserves a real song.`,link:C,category:c},
{text:`The distance between "I should" and "I did" is one click.\n\nCreate their custom song today.`,link:C,category:c},
{text:`Alexa, play the song that made me ugly cry.\n\n"Playing your custom song from SongGift."\n\nThat's the future.`,link:C,category:c},
{text:`They held you up when you wanted to fall down.\n\nHold them up with a song that says "Thank you for being my strength."`,link:C,category:c},
{text:`A book has chapters.\n\nA life has moments.\n\nA custom song captures the moments that matter most.`,link:C,category:c},
{text:`You text them "thinking of you."\n\nImagine sending them a SONG that says "thinking of every moment with you."`,link:C,category:c},
{text:`It's 2025 and people are still giving gift cards?\n\nBe the person who gives a custom song.\n\nBe the legend.`,link:C,category:c},
{text:`Some feelings are too big for a caption.\n\nToo deep for a text.\n\nBut perfect for a song.`,link:C,category:c},
{text:`The people you love won't be here forever.\n\nGive them a song while they can still hear it. Today.`,link:C,category:c},
{text:`A ring is a symbol.\n\nA custom song is the meaning BEHIND the symbol.\n\nGive both. Or just the song. It's enough.`,link:C,category:c},
{text:`Your love story has plot twists, character development, and a happy ending.\n\nAll it needs is a soundtrack.`,link:C,category:c},
{text:`They'll set it as their alarm.\n\nWaking up to a song about how much they're loved? Best morning ever.`,link:C,category:c},
{text:`A voicemail says you called.\n\nA custom song says you put your whole heart into it.`,link:C,category:c},
{text:`Dear person reading this:\n\nSomeone in your life needs a custom song.\n\nYou already know who.\n\nGo.`,link:C,category:c},
{text:`The best investment you'll make this year isn't financial.\n\nIt's emotional.\n\nIt's a $79 custom song.`,link:C,category:c},
{text:`A custom song makes ordinary days feel extraordinary.\n\nBecause every day with that person IS extraordinary.`,link:C,category:c},
{text:`They won't just hear notes.\n\nThey'll hear "I love you" in a way no one has ever said it before.`,link:C,category:c},
{text:`You can take a thousand photos.\n\nBut a custom song captures the one thing photos can't — how it FELT.`,link:C,category:c},
{text:`A song doesn't need wifi to make you feel something.\n\nIt just plays. And changes everything.`,link:C,category:c},
{text:`Your love is the kind people write songs about.\n\nSo let's literally write one.`,link:C,category:c},
{text:`They'll listen once and think "wow."\n\nThey'll listen again and think "nobody has ever done this for me."\n\nYou did.`,link:C,category:c},
{text:`The last song on a playlist gets skipped.\n\nA custom song? Never. It's the one they keep coming back to.`,link:C,category:c},
{text:`A billboard costs thousands.\n\nA custom song costs $79.\n\nBoth declare your love loudly.\n\nOnly one makes them cry.`,link:C,category:c},
{text:`Some things you can't return. Exchange. Regift.\n\nA custom song is one of them.\n\nBecause who would WANT to?`,link:C,category:c},
{text:`Every relationship needs a touchstone.\n\nSomething that grounds you. Reminds you.\n\nA custom song is that touchstone.`,link:C,category:c},
{text:`They've heard "I love you" in conversation.\n\nThey've never heard it in a professionally produced song about their life.\n\nUntil now.`,link:C,category:c},
{text:`A custom song is the gift equivalent of "I would do anything for you."\n\nBecause you kind of just did.`,link:C,category:c},
{text:`You're reading this for a reason.\n\nThat person just popped into your head.\n\nOrder their song. Right now.`,link:C,category:c},
{text:`It won't fix everything.\n\nBut for 3 minutes, it makes everything feel perfect.\n\nAnd sometimes that's enough.`,link:C,category:c},
{text:`A love letter gets read once.\n\nA custom song gets played hundreds of times.\n\nSame message. More impact.`,link:C,category:c},
{text:`Your emotions are valid.\n\nYour story is important.\n\nA custom song proves both.`,link:C,category:c},
{text:`The best part of a custom song isn't the first listen.\n\nIt's the 50th.\n\nWhen it still hits just as hard.`,link:C,category:c},
{text:`A gift for the ages.\n\nLiterally. 18 or 80 — a custom song makes everyone feel deeply loved.`,link:C,category:c},
{text:`They don't make gifts like this anymore.\n\nOh wait. We do.\n\nCustom songs. $79. Delivered in 48 hours.`,link:C,category:c},
{text:`In a world of "add to cart," a custom song is the one thing that can't be mass-produced.\n\nBecause it's YOUR story.`,link:C,category:c},
{text:`When they look back at this year, the custom song will be the highlight.\n\nNot the trip. Not the dinner. The song.`,link:C,category:c},
{text:`We don't just sell songs.\n\nWe sell the look on someone's face when they realize how deeply they're loved.`,link:C,category:c},
{text:`Everyone has a story.\n\nNot everyone has a song.\n\nBe the person who gives them one.`,link:C,category:c},
{text:`They'll save it to their phone.\n\nPlay it on Bluetooth.\n\nSend it to their mom.\n\nThat's the custom song lifecycle. And it's beautiful.`,link:C,category:c},
{text:`The checkout takes 2 minutes.\n\nThe impact lasts a lifetime.\n\nThat's the best ROI you'll ever get.`,link:C,category:c},
{text:`There's no wrong time to tell someone they matter.\n\nAnd there's no better way than a custom song.`,link:C,category:c},
{text:`Imagine 10 years from now. They pull up the song. Press play.\n\nAnd they're right back to THIS moment. The moment you gave it to them.`,link:C,category:c},
{text:`You're one song away from being the greatest gift-giver they've ever known.\n\nJust one. Let's make it.`,link:C,category:c},
{text:`A custom song doesn't need a special occasion.\n\n"Because you exist" is occasion enough.`,link:C,category:c},
{text:`The gift they didn't know they needed.\n\nThe gift they'll never want to live without.\n\nA custom song.`,link:C,category:c},
{text:`You know what they love about you?\n\nThe effort.\n\nA custom song is effort turned into art.`,link:C,category:c},
{text:`Today is a good day to make someone feel loved.\n\nStart here.`,link:C,category:c},
{text:`A custom song costs $79.\n\nThe silence after they hear it for the first time?\n\nThat's the part you can't put a price on.`,link:C,category:c},
{text:`Tomorrow isn't promised.\n\nBut a custom song promises them this: someone loved them enough to make it.`,link:C,category:c},
{text:`Your legacy isn't just what you did.\n\nIt's how you made people feel.\n\nA custom song makes them feel everything.`,link:C,category:c},
{text:`Ready to create something unforgettable?\n\nA custom song starts with your story.\n\nTell us yours.`,link:C,category:c},
{text:`There are 8 billion people on this planet.\n\nOnly one of them gets this custom song.\n\nMake sure it's the right one.`,link:C,category:c},
{text:`A custom song is a promise set to music.\n\n"I love you. I see you. I remember."\n\nPress play. Feel it all.`,link:C,category:c},
{text:`If you're still reading, you already know who needs a custom song.\n\nStop scrolling. Start creating.\n\nThey're waiting.`,link:C,category:c},
{text:`No pressure. But also?\n\nA custom song will be the best gift you've ever given.\n\nSo maybe a little pressure.`,link:C,category:c},
{text:`And when the song ends?\n\nYou'll look at each other.\n\nAnd everything will make sense.\n\nThat's a custom song.`,link:C,category:c},
{text:`The world doesn't need more noise.\n\nIt needs more meaning.\n\nA custom song is meaning — distilled into melody.`,link:C,category:c},
{text:`Every day, someone falls in love.\n\nEvery day, someone misses someone.\n\nEvery day, a custom song captures both.`,link:C,category:c},
{text:`If you could freeze one moment forever… a custom song does exactly that.\n\nIn the most beautiful way possible.`,link:C,category:c},
{text:`They'll add it to a playlist called "songs that make me feel things."\n\nExcept this one? This one tops the list.`,link:C,category:c},
{text:`A relationship is built on moments.\n\nA custom song collects the best ones and puts them on repeat.`,link:C,category:c},
{text:`The most meaningful thing you'll do today might be a 2-minute form.\n\nBecause it creates a song. For someone you love. Forever.`,link:C,category:c},
{text:`Let's be honest.\n\nYou already know this is a good idea.\n\nThe only question is: who gets the song?`,link:C,category:c},
{text:`We don't sell products.\n\nWe sell goosebumps, happy tears, and "I've never felt so loved" moments.\n\nStarting at $79.`,link:C,category:c},
{text:`Your story. Their song. Your love.\n\nThree ingredients. One masterpiece.\n\nCreate it now.`,link:C,category:c},
{text:`The clock is ticking. Not on a sale.\n\nOn moments you could be giving them something extraordinary.\n\nDon't wait.`,link:C,category:c},
{text:`Final thought for today:\n\nSomeone you love deserves a custom song.\n\nAnd you're the only one who can make it happen.`,link:C,category:c},
];
