import { Post, S } from './types';
const C = `${S}/create`;
const c = 'engagement';

export const engagement: Post[] = [
{text:`Question for the couples: What's one tiny moment in your relationship that nobody else would think is special — but means the world to you?\n\nMaybe it's the way they always save the last bite for you. Or how they put their hand on your knee during long drives. Or the song that was playing the first time you kissed.\n\nThose moments? That's what goes into a custom song. The stuff nobody else would know to include. The details that make you YOURS.\n\nDrop your moment below 👇 You might inspire someone's next song.\n\n#couples #relationships #lovemoments #customsong #couplesoftiktok`,link:C,category:c},

{text:`Tag someone who deserves to have a song written about them. 👇\n\nNot a famous someone. YOUR someone.\n\nThe person who shows up every single day without asking for credit. The one who loves you in a way that's quiet but constant. The one you couldn't imagine your life without.\n\nThey probably don't know how much they mean to you. A custom song makes sure they never have to wonder.\n\n$79. 3 minutes. Every feeling you've been holding in — finally released.\n\n#tagsomeone #loveyou #customsong #personalizedgifts #appreciation`,link:C,category:c},

{text:`Be honest: When's the last time you made someone feel truly, genuinely special?\n\nNot "I got you a gift card" special.\n\nLike... tears in their eyes, hand over their mouth, "I can't believe you did this" special?\n\nIf it's been a while, this is your sign.\n\nA custom song takes every beautiful thing about your relationship and puts it into music. Their name. Your memories. The feelings you struggle to say out loud.\n\nWhen they press play and realize it's about THEM? That's the moment.\n\nDon't wait for a holiday. Make someone feel special TODAY.\n\n#makethemcry #lovegift #customsong #surprisegift #relationships`,link:C,category:c},

{text:`What would you say to someone you love if you had 3 minutes and they had to listen?\n\nNot a quick "love you" as you walk out the door. Not a text with a heart emoji.\n\n3 uninterrupted minutes where you get to say everything.\n\nThe things you think but never say. The moments that changed you. The reasons you'd choose them again every single time.\n\nThat's a custom song.\n\nYou give us the words. We give them the music. They get a gift that says everything you've been carrying.\n\nWhat would YOUR 3 minutes say?\n\n#love #customsong #relationships #giftideas #personalizedgifts`,link:C,category:c},

{text:`Parents of adult children — when's the last time your kid really told you what you mean to them?\n\nNot a rushed "thanks Mom" or "love you Dad." But really, truly expressed how your sacrifices shaped their life?\n\nIf you're the adult child reading this: they're waiting. They won't say it, but they're waiting to hear it.\n\nA custom song from you to your parents — mentioning the specific things they did, the moments they don't think you remember — that's the gift that breaks them in the best way.\n\nYour dad will pretend he's not crying. He is.\n\n#momsofinstagram #dadsoftiktok #parentlove #customsong #familygift`,link:`${S}/custom-song-for-mom`,category:c},

{text:`Raise your hand if you're TERRIBLE at expressing your feelings out loud. 🙋\n\nYou feel everything deeply. You love hard. But when it comes to actually SAYING it? The words get stuck.\n\nYou write it in a text then delete it. You practice in the mirror and it sounds dumb. You want to say "you're the best thing that ever happened to me" but what comes out is "you too."\n\nA custom song says it FOR you. All you have to do is share the memories and feelings — we turn them into something beautiful.\n\nFor everyone who loves deeply but struggles to say it: this is for you.\n\n#introvert #loveisnoteasy #customsong #expressyourself #giftsforhim #giftsforher`,link:C,category:c},

{text:`Real question: If you could go back and relive ONE moment with someone you love — what would it be?\n\nThe first time they said "I love you"? Dancing in the kitchen at midnight? That road trip where everything went wrong but it didn't matter?\n\nWhatever your answer is — that's the kind of moment that belongs in a custom song.\n\nBecause a song doesn't let you relive it. It does something better. It freezes it. Keeps it alive. Makes it playable whenever you need to feel close to that moment again.\n\nWhat's your moment? 👇\n\n#memories #lovemoments #nostalgia #customsong #personalgifts`,link:C,category:c},

{text:`POV: It's your anniversary. You hand them a small card. Inside it just says "Press Play" with a QR code.\n\nThey scan it. A song starts.\n\nThey hear their name. They hear the story of how you met. The lyrics mention the restaurant from your first date. The trip that changed everything. The inside joke nobody else would get.\n\nThey look at you. Eyes full.\n\n"You made me a song?"\n\nNo — you made them a memory they can replay forever.\n\nThat's a custom song. That's the anniversary gift that wins. Every year.\n\n$79. Link in bio.\n\n#anniversary #couplesgoals #surprisegift #customsong #lovesong #romanticgift`,link:C,category:c},
];
