import { Post, S } from './types';

// ─── FUNNY (60 posts) ─────────────────────────────────────
const FU = `${S}/funny-song-gift`;
export const funny: Post[] = [
{text:`We don't just do love songs. We do FUNNY songs too. 😂\n\nWant a song about how your friend can't cook? We got you.`,link:FU,category:'funny'},
{text:`A custom song about their weirdest habit?\n\nYep. We do that. And it's hilarious.`,link:FU,category:'funny'},
{text:`"I got a song roasting my brother and he can't stop playing it." 💀\n\nFunny custom songs are the gift that keeps on giving.`,link:FU,category:'funny'},
{text:`Looking for a gift that'll make them laugh AND cry?\n\nA funny personalized song hits both. Every. Single. Time.`,link:FU,category:'funny'},
{text:`Best friend's birthday? Forget a card.\n\nGet them a song about that time they locked their keys in the car. Again.`,link:FU,category:'funny'},
{text:`We wrote a song about someone's dog obsession and they said it was the best gift ever.\n\nYour turn.`,link:FU,category:'funny'},
{text:`Need a retirement roast song? A bachelor party anthem? A "you're getting old" birthday jam?\n\nWe literally do it all.`,link:FU,category:'funny'},
{text:`The funniest gift you can give someone? A song about their most embarrassing moment.\n\nSet to a banger beat.`,link:FU,category:'funny'},
{text:`Custom funny songs: because some people don't need romance, they need to be roasted. With love. In a song.`,link:FU,category:'funny'},
{text:`"The song about my husband's snoring is now his alarm clock." 😂\n\nFunny custom songs hit different.`,link:FU,category:'funny'},
{text:`Your friend group has inside jokes nobody else gets.\n\nWe'll turn them into a song everyone loves.`,link:FU,category:'funny'},
{text:`A love song is sweet.\n\nA roast song is legendary.\n\nWe do both. 🎤`,link:FU,category:'funny'},
{text:`"My kids got me a song about my bad cooking and I've never laughed harder."\n\nFunny songs = family bonding.`,link:FU,category:'funny'},
{text:`Office party? Get a custom song roasting the boss. (Lovingly. Mostly.)`,link:FU,category:'funny'},
{text:`The best gifts aren't always serious.\n\nSometimes they're a custom song about your best friend's irrational fear of pigeons.`,link:FU,category:'funny'},
{text:`We made a song about someone who burns toast every morning.\n\nThey play it every morning while burning toast.\n\nFull circle.`,link:FU,category:'funny'},
{text:`Funny. Heartfelt. Embarrassing. Nostalgic.\n\nA custom song can be ALL of these at once.\n\nThat's the magic.`,link:FU,category:'funny'},
{text:`Bachelor party needs a soundtrack?\n\nA custom funny song about the groom is the ultimate move.`,link:FU,category:'funny'},
{text:`Your friend talks about their cat like it's their child?\n\nWe'll write a song about it. And it'll be amazing.`,link:FU,category:'funny'},
{text:`Some gifts make you cry.\n\nThis one makes you cry LAUGHING.\n\nFunny custom songs, starting at $79.`,link:FU,category:'funny'},
{text:`"We got our dad a song about his golf game and the whole family lost it."\n\nFunny songs bring people together.`,link:FU,category:'funny'},
{text:`Your group chat has the funniest stories.\n\nImagine those stories… in a professional song.\n\nThat's what we do.`,link:FU,category:'funny'},
{text:`Serious songs are beautiful.\n\nBut funny songs? Those get SHARED. Tagged. Replayed at every gathering.`,link:FU,category:'funny'},
{text:`We've written songs about:\n- Terrible parking\n- Obsessive plant parents\n- Someone's 47th pair of sneakers\n\nNothing is off limits.`,link:FU,category:'funny'},
{text:`A funny custom song is the gift that makes them laugh so hard they snort.\n\nAnd then play it again. And again.`,link:FU,category:'funny'},
];

// ─── FRIENDSHIP (30 posts) ────────────────────────────────
const FR = `${S}/friendship-song-gift`;
const BFF = `${S}/custom-song-for-best-friend`;
export const friendship: Post[] = [
{text:`Your best friend has been there through it all.\n\nGive them a song that says "I'd be lost without you."`,link:FR,category:'friendship'},
{text:`Best friends don't need expensive gifts. They need to know they matter.\n\nA custom song says it louder than anything.`,link:BFF,category:'friendship'},
{text:`They were there for the breakdowns AND the breakthroughs.\n\nA custom song is the ultimate "thank you" to your ride-or-die.`,link:FR,category:'friendship'},
{text:`Your best friend knows all your secrets.\n\nA custom song knows all theirs — and turns them into music.`,link:BFF,category:'friendship'},
{text:`"My best friend got me a custom song and I haven't stopped crying."\n\nFriendship goals. Gift goals. Life goals.`,link:FR,category:'friendship'},
{text:`They're the family you chose.\n\nGive them a song that says "I'd choose you every time."`,link:BFF,category:'friendship'},
{text:`The group trip. The 3am texts. The "I've got your back" moments.\n\nAll of it — in a custom song for your best friend.`,link:FR,category:'friendship'},
{text:`Your friendship has survived everything.\n\nIt deserves its own anthem.`,link:BFF,category:'friendship'},
{text:`Some friendships are once in a lifetime.\n\nA custom song makes sure they know that.`,link:FR,category:'friendship'},
{text:`They held your hair back. Drove you home. Told you the truth when no one else would.\n\nThat deserves a song.`,link:BFF,category:'friendship'},
{text:`A matching necklace is cute.\n\nA matching song about your friendship? LEGENDARY.`,link:FR,category:'friendship'},
{text:`You've been through everything together.\n\nWeddings. Breakups. Promotions. Failures. All of it.\n\nCelebrate it in a song.`,link:BFF,category:'friendship'},
{text:`Your best friend already knows you love them.\n\nBut HEARING it in a song? That's a different level of emotion.`,link:FR,category:'friendship'},
{text:`The friend who shows up every time deserves something just as reliable.\n\nA custom song they can play whenever they need a reminder.`,link:BFF,category:'friendship'},
{text:`Friendship isn't always glamorous.\n\nSometimes it's ugly crying on FaceTime.\n\nA custom song celebrates ALL of it.`,link:FR,category:'friendship'},
];

// ─── FAMILY (daughter, son, grandparents, sister, brother, pet, teacher) ──
export const family: Post[] = [
{text:`Your daughter is growing up too fast.\n\nA personalized song freezes your favorite moments forever.`,link:`${S}/custom-song-for-daughter`,category:'daughter'},
{text:`She'll always be your little girl.\n\nA custom song tells her that — no matter how old she gets.`,link:`${S}/custom-song-for-daughter`,category:'daughter'},
{text:`From first steps to first heartbreak, you've been there.\n\nA custom song for your daughter celebrates every chapter.`,link:`${S}/custom-song-for-daughter`,category:'daughter'},
{text:`Your daughter changed your world the moment she arrived.\n\nGive her a song that tells her how.`,link:`${S}/custom-song-for-daughter`,category:'daughter'},
{text:`She's fierce. She's kind. She's everything you hoped she'd be.\n\nA custom song for the daughter who makes you proud daily.`,link:`${S}/custom-song-for-daughter`,category:'daughter'},
{text:`Daddy-daughter dance? Play a custom song written about YOUR bond.\n\nThere won't be a dry eye in the room.`,link:`${S}/custom-song-for-daughter`,category:'daughter'},
{text:`Your son might act like he's too cool for feelings.\n\nBut a custom song from Mom or Dad? That hits different.`,link:`${S}/custom-song-for-son`,category:'son'},
{text:`He's growing into someone incredible.\n\nA custom song tells your son you see it — and you're proud.`,link:`${S}/custom-song-for-son`,category:'son'},
{text:`From little league to big dreams.\n\nA custom song for your son captures the whole journey.`,link:`${S}/custom-song-for-son`,category:'son'},
{text:`He'll pretend it's no big deal.\n\nThen he'll play it when no one's watching. And feel everything.`,link:`${S}/custom-song-for-son`,category:'son'},
{text:`Your son is your greatest adventure.\n\nGive him a song that says "I'm grateful for every moment."`,link:`${S}/custom-song-for-son`,category:'son'},
{text:`Grandparents gave you unconditional love.\n\nGive them a song that says "You shaped who I am."`,link:`${S}/custom-song-for-grandparents`,category:'grandparents'},
{text:`They spoiled you with love, cookies, and wisdom.\n\nA custom song spoils them right back.`,link:`${S}/custom-song-for-grandparents`,category:'grandparents'},
{text:`Grandma's stories. Grandpa's wisdom.\n\nAll captured forever in a custom song.`,link:`${S}/custom-song-for-grandparents`,category:'grandparents'},
{text:`They won't need another blanket or mug.\n\nThey need to know they're loved. A song does that.`,link:`${S}/custom-song-for-grandparents`,category:'grandparents'},
{text:`Your grandparents' love story probably inspired yours.\n\nHonor it with a custom song.`,link:`${S}/custom-song-for-grandparents`,category:'grandparents'},
{text:`Your sister has been your ride-or-die since day one.\n\nA custom song about your bond is the gift she never knew she needed.`,link:`${S}/custom-song-for-sister`,category:'sister'},
{text:`From sharing a room to sharing a life — a custom song for your sister celebrates every fight and every hug.`,link:`${S}/custom-song-for-sister`,category:'sister'},
{text:`She borrowed your clothes. Stole your spotlight. Became your best friend.\n\nGive your sister a song for all of it.`,link:`${S}/custom-song-for-sister`,category:'sister'},
{text:`Sisters fight. Sisters make up. Sisters love harder than anyone.\n\nA custom song honors that bond.`,link:`${S}/custom-song-for-sister`,category:'sister'},
{text:`Your sister has seen you at your worst and loved you at your best.\n\nReturn the favor with a custom song.`,link:`${S}/custom-song-for-sister`,category:'sister'},
{text:`Brothers don't say "I love you" enough.\n\nA custom song says it without the awkwardness.`,link:`${S}/custom-song-for-brother`,category:'brother'},
{text:`He was your first rival and your first ally.\n\nA custom song for your brother honors both roles.`,link:`${S}/custom-song-for-brother`,category:'brother'},
{text:`From wrestling in the backyard to having each other's backs forever.\n\nA custom song for your brother.`,link:`${S}/custom-song-for-brother`,category:'brother'},
{text:`Your brother taught you how to be tough.\n\nA custom song teaches him it's okay to be soft.`,link:`${S}/custom-song-for-brother`,category:'brother'},
{text:`He'd never ask for a sentimental gift.\n\nThat's exactly why a custom song hits so hard.`,link:`${S}/custom-song-for-brother`,category:'brother'},
{text:`Your pet can't understand the words.\n\nBut YOU can. And you'll cry.\n\nA custom song for your fur baby. 🐾`,link:`${S}/custom-song-for-pet`,category:'pet'},
{text:`They don't live as long as we'd like.\n\nBut a custom song about your pet preserves the love forever.`,link:`${S}/custom-song-for-pet`,category:'pet'},
{text:`Your dog greeted you like a hero every day.\n\nA custom song greets that memory with the same energy. 🐕`,link:`${S}/custom-song-for-pet`,category:'pet'},
{text:`Whether they have paws, fins, or feathers — your pet deserves a song.\n\nYes, we do pet songs. And they're adorable.`,link:`${S}/custom-song-for-pet`,category:'pet'},
{text:`Teachers change lives.\n\nA custom song tells yours how much they changed yours.`,link:`${S}/custom-song-for-teacher`,category:'teacher'},
{text:`They stayed late. Believed in you. Pushed you to be better.\n\nA custom song for the teacher who made a difference.`,link:`${S}/custom-song-for-teacher`,category:'teacher'},
{text:`End-of-year gift for your favorite teacher?\n\nSkip the mug. Give them a custom song they'll treasure.`,link:`${S}/custom-song-for-teacher`,category:'teacher'},
{text:`A baby is on the way and the love is already overflowing.\n\nCapture it in a custom song for the new parents.`,link:`${S}/baby-shower-song-gift`,category:'baby'},
{text:`A baby shower gift they'll actually keep?\n\nA custom song about the new little one. 🍼`,link:`${S}/baby-shower-song-gift`,category:'baby'},
{text:`Welcome to the world, little one.\n\nA custom baby song captures the excitement and love of a growing family.`,link:`${S}/baby-shower-song-gift`,category:'baby'},
{text:`Turning 16 is a big deal.\n\nMake it unforgettable with a custom Sweet 16 song.`,link:`${S}/sweet-16-song-gift`,category:'sweet-16'},
{text:`Sweet 16 = sweet song.\n\nA custom song for the birthday girl that captures who she is right now.`,link:`${S}/sweet-16-song-gift`,category:'sweet-16'},
{text:`A Quinceañera deserves a song as special as the moment.\n\nCelebrate her journey with a custom song.`,link:`${S}/quinceanera-song-gift`,category:'quinceanera'},
{text:`15 years of love, growth, and becoming.\n\nA custom Quinceañera song celebrates all of it.`,link:`${S}/quinceanera-song-gift`,category:'quinceanera'},
{text:`Sometimes "thank you" isn't enough.\n\nA custom song of gratitude goes deeper than words.`,link:`${S}/thank-you-song-gift`,category:'thank-you'},
{text:`Thank you notes fade.\n\nA thank-you song plays forever.`,link:`${S}/thank-you-song-gift`,category:'thank-you'},
{text:`They did something that changed your life.\n\nA custom thank-you song tells them so.`,link:`${S}/thank-you-song-gift`,category:'thank-you'},
{text:`Actions speak louder than words. But a heartfelt apology song?\n\nThat speaks volumes.`,link:`${S}/apology-song-gift`,category:'apology'},
{text:`Sorry doesn't always cut it.\n\nBut a personalized apology song shows real effort and real emotion.`,link:`${S}/apology-song-gift`,category:'apology'},
{text:`Corporate gifts should inspire, not collect dust.\n\nA custom song for your team celebrates wins like nothing else.`,link:`${S}/corporate-song-gift`,category:'corporate'},
{text:`Team building event? Company anniversary?\n\nA custom corporate song brings everyone together.`,link:`${S}/corporate-song-gift`,category:'corporate'},
];

// ─── TRUST / SOCIAL PROOF (50 posts) ──────────────────────
const C = `${S}/create`;
export const trust: Post[] = [
{text:`Studio-quality production. Custom lyrics. Delivered in 3–5 business days.\n\nStarting at $79. Your love story deserves to be heard.`,link:C,category:'trust'},
{text:`Custom song + cover art + lyric sheet + MP3 & WAV = $79.\n\nThe most meaningful gift you'll ever give.`,link:C,category:'trust'},
{text:`Not sure if a custom song is worth it?\n\nListen to samples and hear the quality for yourself.`,link:`${S}/playlist`,category:'trust'},
{text:`30-day money-back guarantee. Unlimited revisions. 48-hour delivery.\n\nZero risk. All love.`,link:C,category:'trust'},
{text:`Pop. Country. R&B. Acoustic. Worship. Rap. Cinematic.\n\nWhatever genre speaks to you, we create it.`,link:C,category:'trust'},
{text:`How it works:\n\n1. Tell us your story\n2. We create your song\n3. You make someone cry (happy tears)\n\nSimple.`,link:C,category:'trust'},
{text:`Your custom song includes:\n✅ Original lyrics\n✅ Studio recording\n✅ Cover art\n✅ Lyric sheet\n✅ MP3 & WAV files\n\nAll for $79.`,link:C,category:'trust'},
{text:`Need it fast? Express delivery gets your song in 24 hours.\n\nPerfect for last-minute gift emergencies.`,link:C,category:'trust'},
{text:`Every song we create is 100% original.\n\nNo templates. No recycled lyrics. Just YOUR story, set to music.`,link:C,category:'trust'},
{text:`Not a musician? No problem.\n\nYou bring the story. We bring the talent.\n\nTogether, we make magic.`,link:C,category:'trust'},
{text:`Still thinking about it?\n\nThe only people who regret a custom song are the ones who didn't order one.`,link:C,category:'trust'},
{text:`$79 for a gift they'll listen to for years vs. $79 for something they'll forget in a week.\n\nThe choice is clear.`,link:C,category:'trust'},
{text:`We take your memories seriously.\n\nEvery detail you share becomes a lyric they'll sing in the shower.`,link:C,category:'trust'},
{text:`The process is simple:\n\n📝 Fill out the form\n🎵 We create your song\n📧 Delivered to your inbox\n\n3–5 business days. Done.`,link:C,category:'trust'},
{text:`We don't do cookie-cutter.\n\nEvery song is handcrafted, from the first note to the last word.`,link:C,category:'trust'},
{text:`What happens after you order:\n\n1. We read your story\n2. We get emotional\n3. We write an incredible song\n4. You get emotional\n\nIt's a whole cycle of feelings.`,link:C,category:'trust'},
{text:`Unlimited revisions until you love it.\n\nWe don't stop until your song is perfect.`,link:C,category:'trust'},
{text:`Custom songs for every occasion:\n🎂 Birthday\n💍 Wedding\n❤️ Anniversary\n🎓 Graduation\n😂 Funny\n🕊️ Memorial\n\nWe do it all.`,link:C,category:'trust'},
{text:`Your story matters.\n\nWe treat every order like it's the most important song we've ever made. Because to you, it is.`,link:C,category:'trust'},
{text:`Digital delivery means no shipping stress.\n\nYour custom song arrives in your inbox, ready to make someone's whole year.`,link:C,category:'trust'},
{text:`We've turned breakups, makeups, proposals, and inside jokes into songs.\n\nWhat's YOUR story?`,link:C,category:'trust'},
{text:`A custom song takes 2 minutes to order.\n\nBut the memory it creates? That lasts a lifetime.`,link:C,category:'trust'},
{text:`100% satisfaction guarantee.\n\nIf you're not happy, you don't pay. Simple as that.`,link:C,category:'trust'},
{text:`We create in every genre:\n🎸 Acoustic\n🎹 Pop\n🤠 Country\n🎷 R&B\n🙏 Worship\n🎤 Rap\n🎬 Cinematic\n\nPick the vibe. We handle the rest.`,link:C,category:'trust'},
{text:`The gift you can give from anywhere in the world.\n\nLong distance? Deployed? Traveling?\n\nA custom song bridges every gap.`,link:C,category:'trust'},
{text:`They'll ask how much it cost.\n\nYou'll say $79.\n\nThey won't believe it.\n\nNeither will they, when they hear it.`,link:C,category:'trust'},
{text:`One form. One story. One song.\n\nThat's all it takes to create something unforgettable.`,link:C,category:'trust'},
{text:`We pour our heart into every song.\n\nBecause you poured yours into the story behind it.`,link:C,category:'trust'},
{text:`Custom songs make people feel SEEN.\n\nAnd in a world that's always moving, being seen is the greatest gift.`,link:C,category:'trust'},
{text:`Delivered digitally. Kept forever.\n\nA custom song is the gift that never gathers dust.`,link:C,category:'trust'},
];
