import { Post, S } from './types';
const C = `${S}/create`;
const c = 'hooks';

export const hooks: Post[] = [
{text:`Stop buying gifts people forget about in a week.\n\nSeriously. Think about the last 5 gifts you received. How many do you remember? How many actually made you feel something?\n\nNow think about a song that was written about YOU. Your name. Your memories. Your relationship with someone you love.\n\nYou'd never forget it. You'd play it in the car. In bed at night. You'd send it to your mom. You'd cry the first time you heard it.\n\nThat's the difference between a gift and a GIFT.\n\nCustom songs starting at $79 — cheaper than the perfume she'll forget about by February.\n\n#giftideas #personalizedgifts #customsong #giftsforher #giftsforhim #meaningfulgifts`,link:C,category:c},

{text:`"I didn't know what to get her."\n\nThat's what he said. Another anniversary coming up, another panic. She's not the jewelry type. She has everything she needs. He'd already done the fancy dinner, the flowers, the weekend trip.\n\nSo he tried something different. He wrote down their story — how they met at that coffee shop, the awful first date, the road trip where they fell in love — and let someone turn it into a song.\n\n3 minutes. Their whole love story in music.\n\nShe listened to it 11 times the first night.\n\nIf you're stuck on what to give someone who has everything — they don't have this yet.\n\n#anniversarygift #giftsforwife #customsong #personalgifts #giftsforher`,link:`${S}/custom-song-for-wife`,category:c},

{text:`The gift that ACTUALLY makes people cry (in the best way):\n\nNot diamonds. Not a vacation. Not a surprise party.\n\nA song. Written about them. About your specific memories together.\n\nWhen you hear a generic love song on the radio, you feel something. Now imagine hearing a song where the lyrics are YOUR inside jokes. YOUR first date. YOUR person's name.\n\nIt hits completely different.\n\nEvery single person who receives a custom song has the same reaction: hand over mouth, tears, "how did you do this?"\n\nEvery. Single. Time.\n\n$79. Best money you'll ever spend on a gift.\n\n#customsong #personalizedgifts #bestgift #giftideas #makethemcry`,link:C,category:c},

{text:`Hot take: The best gift you can give someone isn't something they can hold.\n\nIt's something they can FEEL.\n\nA custom song isn't a product. It's an experience. It's 3 minutes where someone feels like the most important person in the world because every single word is about THEM.\n\nTheir memories. Their quirks. Their relationship with you. All set to music.\n\nPhysical gifts depreciate. Experiences fade. But a song about your love story? That appreciates. Every year it means more.\n\n10 years from now, you won't remember what candle you bought them. But you'll both remember the song.\n\n#gifts #customsong #experiencegifts #personalgifts #meaningfulgifts`,link:C,category:c},

{text:`Unpopular opinion: Expensive gifts are lazy.\n\nThrowing money at a problem isn't thoughtful. It's convenient.\n\nYou know what's thoughtful? Sitting down and writing out every memory, every moment, every reason you love someone — and turning it into a song they'll keep forever.\n\nThe gift that costs $79 but took you 30 minutes of real, genuine reflection on your relationship? That beats the $500 necklace she'll wear twice.\n\nEvery time.\n\nThoughtfulness > price tag. Always.\n\n#unpopularopinion #giftgiving #customsong #thoughtfulgifts #personalizedgifts`,link:C,category:c},

{text:`If you've ever said "they're impossible to shop for" — read this.\n\nThe reason they're impossible to shop for is because they don't need THINGS. They have things. What they need is to feel seen. Appreciated. Known.\n\nA custom song does exactly that. When the lyrics mention the trip you took together, the joke only you two understand, the Tuesday night ritual nobody else knows about — that's not a gift. That's EVIDENCE that you pay attention.\n\nAnd for someone who "has everything," being truly known is the one thing money usually can't buy.\n\nExcept now it can. $79.\n\n#hardtoshopfor #giftideas #customsong #personalgifts #giftsforpeoplewhohaveeverything`,link:`${S}/blog/best-birthday-gift-ideas-for-someone-who-has-everything`,category:c},

{text:`Your love story deserves better than a Hallmark card.\n\nThink about it — you've been through everything together. The 2am conversations. The fights you survived. The laughs nobody else would understand. The moments that built your entire world.\n\nAnd the best you can do is "To my wonderful wife, love always"?\n\nNah.\n\nYour story deserves to be HEARD. Set to music. Replayed on car rides and slow mornings and every anniversary for the rest of your lives.\n\nA custom song takes everything you feel and turns it into something permanent.\n\n#anniversary #lovesong #customsong #wifey #couplesgoals #love`,link:C,category:c},

{text:`The difference between a good gift and an UNFORGETTABLE one:\n\nGood gift: Something they like.\nUnforgettable gift: Something that makes them realize how deeply they're loved.\n\nA custom song crosses that line. When someone hears their own memories set to music — their name, their story, the details only you would know — something shifts.\n\nIt's not just "oh that's nice." It's "you saw me. You really saw me."\n\nThat's the reaction you want. That's the gift that changes how they feel about themselves, about you, about your relationship.\n\nStarting at $79.\n\n#gifting #customsong #bestgiftever #personalizedgifts #meaningfulgifts`,link:C,category:c},
];
