import { Post, S } from './types';
const C = `${S}/create`;
const c = 'relatable';

export const relatable: Post[] = [
{text:`Things that are romantic but nobody talks about:\n\n• Remembering the small details they mentioned once\n• Keeping a note on your phone of gift ideas for them\n• Noticing when they're having a bad day without them saying it\n• Planning something weeks in advance that references an old memory\n• Getting them a gift that proves you've been listening all year\n\nA custom song is all of these at once. It's 3 minutes of proof that you noticed everything.\n\nThe lyrics reference THEIR memories. THEIR words. Details they forgot they ever told you.\n\nThat's not just romantic. That's a whole love language.\n\n#romance #relationships #loveideas #customsong #datenight #couplesgoals`,link:C,category:c},

{text:`You know that feeling when a song comes on and INSTANTLY you're back in a specific moment?\n\nMaybe it's a summer road trip. Your first apartment. That one night that changed everything.\n\nMusic does something no other medium can — it time-travels. It bypasses your brain and goes straight to your heart.\n\nNow imagine a song that was MADE to trigger those feelings. On purpose. With lyrics about your specific memories, your specific person, your specific love.\n\nEvery time they press play, they're right back in that moment with you.\n\nThat's what a custom song does. It's a time machine disguised as a gift.\n\n#music #nostalgia #memories #customsong #lovesong #gifts`,link:C,category:c},

{text:`Types of gift-givers:\n\n🎁 The Panicker — buys something the night before, wraps it badly, hopes for the best\n\n💳 The Safe Player — gift card. Every time. "At least they can pick what they want"\n\n🛍️ The Overspender — drops $300+ hoping price = love\n\n💝 The Listener — pays attention all year, remembers one thing mentioned in passing 6 months ago, delivers a gift that makes them feel truly known\n\nA custom song is a Listener gift. It proves you paid attention. Noticed the details. Cared enough to capture it all in music.\n\nWhich type are you? (Be honest 😂)\n\n#giftgiving #gifter #relationships #customsong #personalizedgifts`,link:C,category:c},

{text:`Genuine question for the men in relationships:\n\nDo you know what your partner actually wants?\n\nNot what she says ("nothing, I'm fine"). Not what Instagram tells you (designer bags). Not what's safe (flowers).\n\nWhat she ACTUALLY wants is to feel like you SEE her. Like you remember the little things. Like she's not just "wife" or "girlfriend" — she's the specific, unique person you fell in love with.\n\nA custom song references HER stories. HER personality. The things only YOU would know to include.\n\nThat's the gift that makes her call her mom crying (happy tears) before the song even finishes playing.\n\nStart here: $79.\n\n#husbands #boyfriendsoftiktok #giftsforher #customsong #whatshereallywants`,link:`${S}/custom-song-for-wife`,category:c},

{text:`The scariest thing about loving someone deeply?\n\nWorrying that they don't know.\n\nThat you never found the right words. That your daily actions speak for you but maybe not loudly enough. That one day they might wonder "do they really love me THAT much?"\n\nA custom song eliminates that worry. Permanently.\n\nIt takes every feeling you've ever had about them — the overwhelming ones you can't say out loud — and turns them into something they can replay whenever they need reminding.\n\nYou love them. Make sure they KNOW it. In a way they can never unhear.\n\n#love #relationships #deepfeelings #customsong #lovesong #forever`,link:C,category:c},

{text:`Signs you need to order a custom song:\n\n✓ You've been with someone who deserves more than another "normal" gift\n✓ You've thought "how do I show them what they mean to me?"\n✓ You're bad at saying how you feel out loud\n✓ An important occasion is coming up\n✓ You want to be the person who gives the BEST gift anyone's ever received\n✓ You have a love story worth telling\n\nIf you checked even ONE of these — you already know what to do.\n\n$79. Ready in 3-5 days. Their reaction? Priceless.\n\n#customsong #giftideas #personalizedgifts #lovesong #bestgiftever`,link:C,category:c},

{text:`Nobody:\nAbsolutely nobody:\nSomeone getting a custom song for the first time: 😭😭😭\n\nIt's the same reaction every single time:\n1. "What is this?"\n2. "Wait... is this about ME?"\n3. "How did you..."\n4. *ugly crying*\n5. "Play it again."\n6. Proceeds to share with literally everyone they know\n\nThe best part? This happens whether they're 16 or 86. Whether it's a girlfriend, a grandma, or a best friend.\n\nA custom song hits everyone the same way: right in the chest.\n\nBe the reason someone has this reaction.\n\n#customsong #reactionvideo #surprisegift #makethemcry #bestgift`,link:C,category:c},

{text:`Things that sound expensive but aren't:\n\n❌ A custom song written about your love story: $79\n✓ That fancy dinner you forgot about by next week: $150+\n✓ Jewelry she'll wear twice: $200+\n✓ A designer bag that's "the gift": $400+\n✓ A vacation that's over in 3 days: $1000+\n\nA custom song costs less than dinner for two but creates a memory that lasts literally forever.\n\nIt's the most bang-for-your-buck gift that exists. And it's the one they'll actually remember.\n\nJust saying.\n\n#budgetfriendly #giftideas #customsong #smartgifting #cheapbutmeaningful`,link:C,category:c},
];
