import { Post, S } from './types';

// ─── WIFE (60 posts) ──────────────────────────────────────
const W = `${S}/custom-song-for-wife`;
export const wife: Post[] = [
{text:`She's your best friend, your partner, your everything.\n\nSurprise your wife with a custom song that tells her exactly how you feel.`,link:W,category:'wife'},
{text:`She deserves more than "I love you." She deserves a whole song about it.\n\nCreate a personalized song for your wife.`,link:W,category:'wife'},
{text:`Remember your first dance? Your first road trip? That random Tuesday that changed everything?\n\nTurn it into a song for her.`,link:W,category:'wife'},
{text:`She does everything for everyone. Now it's her turn to feel like the center of the universe.\n\nA custom song for your wife.`,link:W,category:'wife'},
{text:`You married the love of your life. Now give her a song that proves she still takes your breath away.`,link:W,category:'wife'},
{text:`She already knows you love her. But HEARING it in a song? That's a whole different level.`,link:W,category:'wife'},
{text:`Your wife isn't just your partner. She's your muse.\n\nLet us turn your love into a song.`,link:W,category:'wife'},
{text:`She said "yes" to forever. Give her a song that celebrates every moment since.\n\nA custom song for the love of your life.`,link:W,category:'wife'},
{text:`She doesn't need diamonds. She needs to know she's your diamond.\n\nSay it with a song.`,link:W,category:'wife'},
{text:`Every wife deserves to feel like the heroine of her own love story.\n\nA custom song puts her center stage.`,link:W,category:'wife'},
{text:`She held your hand through the hardest days.\n\nGive her a song that holds her heart on the best ones.`,link:W,category:'wife'},
{text:`"I played it for my wife at dinner. She couldn't finish eating because she was crying."\n\nThat's the SongGift effect.`,link:W,category:'wife'},
{text:`She's the calm in your chaos. The laugh when you need it most.\n\nA custom song for the wife who makes everything better.`,link:W,category:'wife'},
{text:`Your wife doesn't want more things. She wants to feel cherished.\n\nA personalized song does exactly that.`,link:W,category:'wife'},
{text:`She made you a better person. You can make her cry (happy tears).\n\nCreate her custom song today.`,link:W,category:'wife'},
{text:`Still in love after all these years? Prove it.\n\nA custom song that says "I'd choose you all over again."`,link:W,category:'wife'},
{text:`The woman who stole your heart deserves a whole song about it.\n\nNot a card. Not flowers. A SONG.`,link:W,category:'wife'},
{text:`She's the reason you smile before you even open your eyes.\n\nGive her something that makes HER smile just as wide.`,link:W,category:'wife'},
{text:`Your love story started with a glance. Let it continue with a melody.\n\nCustom song for your wife — starting at $79.`,link:W,category:'wife'},
{text:`She puts everyone else first. Time to put HER first.\n\nA custom song that says "You are my everything."`,link:W,category:'wife'},
{text:`She already has your last name. Now give her her own song.`,link:W,category:'wife'},
{text:`The way she laughs. The way she cares. The way she loves.\n\nAll of that — in a song made just for her.`,link:W,category:'wife'},
{text:`Anniversary coming up? Forget the restaurant.\n\nBook a custom song and watch her melt.`,link:W,category:'wife'},
{text:`She's the plot twist that made your whole life better.\n\nCelebrate her with a song that tells HER story.`,link:W,category:'wife'},
{text:`She's heard you say "I love you" a million times.\n\nBut she's never heard it sung — in a song written about HER.`,link:W,category:'wife'},
{text:`Behind every great love story is a woman who deserves her own song.\n\nGive your wife that song today.`,link:W,category:'wife'},
{text:`One song. One wife. A million emotions.\n\nCreate her custom song now.`,link:W,category:'wife'},
{text:`She didn't just change your life — she IS your life.\n\nA custom song for the wife who means everything.`,link:W,category:'wife'},
{text:`"My husband got me a custom song and I can't stop playing it. Best gift I've ever received."\n\nYour wife could be next.`,link:W,category:'wife'},
{text:`You fell in love with her for a reason. Actually, a thousand reasons.\n\nWe'll put them all in a song.`,link:W,category:'wife'},
];

// ─── HUSBAND (60 posts) ───────────────────────────────────
const H = `${S}/custom-song-for-husband`;
export const husband: Post[] = [
{text:`He works hard, loves harder, and rarely asks for anything.\n\nGive your husband a song that says "I see everything you do."`,link:H,category:'husband'},
{text:`When's the last time someone made your husband cry happy tears?\n\nA custom song might just do it.`,link:H,category:'husband'},
{text:`He's the rock of your family. Time to show him he's also the star of your love story.`,link:H,category:'husband'},
{text:`Your husband carries the weight of the world without complaining.\n\nCarry him with a song he'll never forget.`,link:H,category:'husband'},
{text:`He says he doesn't want anything. That's because he hasn't been given a custom song.\n\nChange that.`,link:H,category:'husband'},
{text:`A personalized song for your husband = the gift he never knew he needed.\n\nUntil he hears it.`,link:H,category:'husband'},
{text:`He's your safe place. Your Sunday mornings. Your favorite hello.\n\nPut it all in a song.`,link:H,category:'husband'},
{text:`"I played it for my husband in the car. He pulled over because he couldn't see through the tears."\n\nTrue story.`,link:H,category:'husband'},
{text:`Behind every great family is a husband who gives his all.\n\nCelebrate him with something unforgettable.`,link:H,category:'husband'},
{text:`He fixed things around the house. You fix things in his heart.\n\nWith a custom song.`,link:H,category:'husband'},
{text:`Your husband taught you what real love looks like.\n\nA custom song teaches him what gratitude sounds like.`,link:H,category:'husband'},
{text:`Father. Husband. Best friend.\n\nHe's all of these. Give him a song that honors every role.`,link:H,category:'husband'},
{text:`Men rarely get truly personal gifts.\n\nA custom song about HIS story? He'll remember it forever.`,link:H,category:'husband'},
{text:`He held you when you needed it.\n\nNow give him something to hold onto — a song about your love.`,link:H,category:'husband'},
{text:`He's the calm when everything's spinning.\n\nAnchor him with a song that says "You are my everything."`,link:H,category:'husband'},
{text:`Surprise your husband with something that cuts through the noise.\n\nA song that says exactly what your heart feels.`,link:H,category:'husband'},
{text:`He deserves more than a tie on Father's Day.\n\nHe deserves a whole song.`,link:H,category:'husband'},
{text:`The man who married you. Who chose you. Who chooses you every single day.\n\nGive him a song for that.`,link:H,category:'husband'},
{text:`Your husband's strength isn't just physical.\n\nIt's in his patience, his love, his quiet sacrifices. Celebrate it with music.`,link:H,category:'husband'},
{text:`He might not say he loved it right away.\n\nBut he'll play it in the car alone. And cry. And you'll know.`,link:H,category:'husband'},
{text:`"How did you know exactly what to say?" Because it's YOUR words. In a song. For him.\n\nCreate his custom song.`,link:H,category:'husband'},
{text:`He puts the family first. Now put him first — with a custom song that celebrates who he is.`,link:H,category:'husband'},
{text:`Your husband has given you a life full of love.\n\nGive him 3 minutes of pure emotion in return.`,link:H,category:'husband'},
{text:`He's not a man of many words.\n\nGood thing a custom song speaks louder than all of them.`,link:H,category:'husband'},
{text:`Still crazy about your husband after all these years?\n\nLet a custom song prove it in the most beautiful way.`,link:H,category:'husband'},
{text:`He'd never buy this for himself.\n\nThat's exactly why YOU should.`,link:H,category:'husband'},
{text:`A custom song for your husband isn't just a gift.\n\nIt's a love letter set to music.`,link:H,category:'husband'},
{text:`Make your husband feel like the king he is.\n\nA personalized song, crafted from your real love story.`,link:H,category:'husband'},
{text:`You know his favorite food, his bad habits, his secret soft side.\n\nWe'll put it all in a song.`,link:H,category:'husband'},
{text:`The toughest man you know will go soft when he hears this.\n\nA custom song for the husband who has everything except his own song.`,link:H,category:'husband'},
];

// ─── GIRLFRIEND (50 posts) ────────────────────────────────
const GF = `${S}/custom-song-for-girlfriend`;
export const girlfriend: Post[] = [
{text:`She screenshots your sweet texts. Imagine what she'll do when she hears a whole song written about her.`,link:GF,category:'girlfriend'},
{text:`Forget the flowers and the teddy bears.\n\nGive your girlfriend a custom song she'll play on repeat and cry to.`,link:GF,category:'girlfriend'},
{text:`She's the main character of your life.\n\nGive her the soundtrack to prove it.`,link:GF,category:'girlfriend'},
{text:`She posts you on Instagram.\n\nGive her something worth an even bigger post — her own song.`,link:GF,category:'girlfriend'},
{text:`A custom song for your girlfriend is the "I'm serious about us" gift.\n\nNothing says it louder.`,link:GF,category:'girlfriend'},
{text:`She saved your contact as something cute.\n\nNow give her a song that's even cuter.`,link:GF,category:'girlfriend'},
{text:`The FaceTime calls. The late-night "u up?" texts. The butterflies.\n\nWe turn all of it into a song.`,link:GF,category:'girlfriend'},
{text:`She makes you want to be better.\n\nA custom song tells her she already makes you feel like the best version of yourself.`,link:GF,category:'girlfriend'},
{text:`"He got me a custom song and I haven't stopped crying for three days."\n\nThat could be your girlfriend.`,link:GF,category:'girlfriend'},
{text:`She lights up every room she walks into.\n\nA custom song lights up her whole world.`,link:GF,category:'girlfriend'},
{text:`She stole your hoodie. Now steal her heart — with a personalized song about your love.`,link:GF,category:'girlfriend'},
{text:`Your girlfriend doesn't need another necklace.\n\nShe needs to hear how you feel. In a song. With her name in it.`,link:GF,category:'girlfriend'},
{text:`You think about her all the time.\n\nA custom song lets her HEAR those thoughts.`,link:GF,category:'girlfriend'},
{text:`She makes the ordinary feel extraordinary.\n\nGive her something extraordinary in return.`,link:GF,category:'girlfriend'},
{text:`Want to set the bar impossibly high?\n\nGive your girlfriend a custom song. Good luck topping it, everyone else.`,link:GF,category:'girlfriend'},
{text:`She's your peace. Your chaos. Your favorite person.\n\nAll of that — in her very own song.`,link:GF,category:'girlfriend'},
{text:`A playlist of "your songs" is cute.\n\nA song ABOUT her? That's legendary.`,link:GF,category:'girlfriend'},
{text:`She sends you songs that remind her of you.\n\nSend her one that was literally MADE for her.`,link:GF,category:'girlfriend'},
{text:`Your girlfriend already thinks you're sweet.\n\nA custom song makes her think you're the sweetest person alive.`,link:GF,category:'girlfriend'},
{text:`She'll play it for her friends. Her mom. Her group chat.\n\n"LOOK WHAT HE DID."\n\nYeah. You did that.`,link:GF,category:'girlfriend'},
{text:`The most romantic gesture isn't a grand vacation.\n\nIt's a song that says "I know your heart and I love every part of it."`,link:GF,category:'girlfriend'},
{text:`She gave you her heart.\n\nGive her a song she can carry in hers forever.`,link:GF,category:'girlfriend'},
{text:`Roses are temporary. A song about your love story? That's permanent.`,link:GF,category:'girlfriend'},
{text:`She'll play this song on every anniversary, every road trip, every rainy Sunday.\n\nCreate her song now.`,link:GF,category:'girlfriend'},
{text:`Your girlfriend deserves a love story with a soundtrack.\n\nStart writing the first track — with a custom song.`,link:GF,category:'girlfriend'},
];

// ─── BOYFRIEND (50 posts) ─────────────────────────────────
const BF = `${S}/custom-song-for-boyfriend`;
export const boyfriend: Post[] = [
{text:`He pretends he's tough, but a song about your love story?\n\nThat'll get him. Trust us.`,link:BF,category:'boyfriend'},
{text:`He says he doesn't need anything. But he's never been given a custom song.\n\nSurprise him.`,link:BF,category:'boyfriend'},
{text:`A custom song for your boyfriend = the ultimate "you're my person" move.`,link:BF,category:'boyfriend'},
{text:`He'll act casual when you give it to him.\n\nThen he'll play it in his car alone and get emotional. Guaranteed.`,link:BF,category:'boyfriend'},
{text:`Your boyfriend makes you laugh, feel safe, and believe in love.\n\nA custom song is the least he deserves.`,link:BF,category:'boyfriend'},
{text:`He's your ride-or-die. Your 2 AM. Your everything.\n\nGive him a song that says all of it.`,link:BF,category:'boyfriend'},
{text:`He gave you his hoodie. Give him a song.\n\nFair trade? We think so.`,link:BF,category:'boyfriend'},
{text:`"My girlfriend got me a custom song and I'm not crying, you're crying."\n\nEvery boyfriend's response.`,link:BF,category:'boyfriend'},
{text:`He doesn't need another video game or cologne.\n\nHe needs to know how you feel about him. In song form.`,link:BF,category:'boyfriend'},
{text:`You've sent him love songs before.\n\nBut have you sent him one that was WRITTEN about him?`,link:BF,category:'boyfriend'},
{text:`He always puts you first.\n\nTime to put HIM first — with a personalized song about your love.`,link:BF,category:'boyfriend'},
{text:`Your boyfriend is one of a kind.\n\nHis gift should be too.`,link:BF,category:'boyfriend'},
{text:`He texted back immediately. He shows up. He cares.\n\nReward that energy with the most personal gift ever.`,link:BF,category:'boyfriend'},
{text:`A custom song about your boyfriend = instant legend status.\n\nHe'll tell everyone. And play it for everyone.`,link:BF,category:'boyfriend'},
{text:`He makes everything better just by being there.\n\nA custom song says "I noticed, and I'm grateful."`,link:BF,category:'boyfriend'},
{text:`Every boyfriend thinks he's tough.\n\nEvery boyfriend cries at his custom song.\n\nFacts.`,link:BF,category:'boyfriend'},
{text:`You know how he looks at you when he thinks you're not watching?\n\nA custom song makes him feel THAT — every time he presses play.`,link:BF,category:'boyfriend'},
{text:`He's the plot twist you didn't see coming.\n\nGive him a song for changing your story.`,link:BF,category:'boyfriend'},
{text:`He remembers the little things.\n\nTime to show him you remember them too — in a custom song.`,link:BF,category:'boyfriend'},
{text:`Your boyfriend called you his person.\n\nNow give him a song that confirms he's yours.`,link:BF,category:'boyfriend'},
{text:`He held your hand when no one was watching.\n\nGive him a song that holds his heart when you're not around.`,link:BF,category:'boyfriend'},
{text:`A personalized song for your boyfriend is the gift that keeps giving.\n\nEvery listen, he falls a little harder.`,link:BF,category:'boyfriend'},
{text:`He makes the mundane magical.\n\nGrocery runs feel like dates. Silence feels like love.\n\nPut that feeling in a song.`,link:BF,category:'boyfriend'},
{text:`He's the reason your standards are sky-high.\n\nReward him with a sky-high gift — his own custom song.`,link:BF,category:'boyfriend'},
{text:`Your boyfriend won't admit it.\n\nBut a song about your relationship will be his most prized possession.`,link:BF,category:'boyfriend'},
];

// ─── MOM (60 posts) ───────────────────────────────────────
const MO = `${S}/custom-song-for-mom`;
export const momPosts: Post[] = [
{text:`She raised you, supported you, loved you through everything.\n\nA custom song for Mom says "thank you" in a way nothing else can.`,link:MO,category:'mom'},
{text:`Mom doesn't want more "stuff." She wants to know she matters.\n\nGive her a song that says it all.`,link:MO,category:'mom'},
{text:`If your mom says "you don't have to get me anything" — she's lying.\n\nGet her a custom song. Watch the tears.`,link:MO,category:'mom'},
{text:`She taught you how to love. Now show her what you learned.\n\nA personalized song for the woman who gave you everything.`,link:MO,category:'mom'},
{text:`Mom already has your school photos in a frame.\n\nNow give her something she can LISTEN to and cry about.`,link:MO,category:'mom'},
{text:`She's been your biggest fan since day one.\n\nTime to be hers — with a custom song that says everything your heart holds.`,link:MO,category:'mom'},
{text:`She wiped your tears. Held your hand. Stayed up late worrying.\n\nA custom song repays even a fraction of that love.`,link:MO,category:'mom'},
{text:`"My daughter got me a custom song and I've listened to it every morning since."\n\nThat could be YOUR mom.`,link:MO,category:'mom'},
{text:`She made home feel like the safest place on earth.\n\nGive her a song that makes her feel safe in your love.`,link:MO,category:'mom'},
{text:`Your mom gave you life.\n\nGive her a song about the life you've built — because of her.`,link:MO,category:'mom'},
{text:`She never asked for credit. She never kept score.\n\nA custom song gives her the recognition she deserves.`,link:MO,category:'mom'},
{text:`She's the first voice you ever heard.\n\nLet a custom song be the voice that tells her she's everything.`,link:MO,category:'mom'},
{text:`She could hear your cry from three rooms away.\n\nNow she can hear your love from anywhere — through a custom song.`,link:MO,category:'mom'},
{text:`Nobody loves you like your mom does.\n\nReturn the favor with a song she'll never stop playing.`,link:MO,category:'mom'},
{text:`A bouquet lasts a week. A spa day lasts a day.\n\nA custom song for Mom lasts forever.`,link:MO,category:'mom'},
{text:`She fought battles you never even knew about.\n\nHonor her strength with a song crafted from your deepest gratitude.`,link:MO,category:'mom'},
{text:`Your mom's favorite gift? Anything from the heart.\n\nA custom song IS the heart. In audio form.`,link:MO,category:'mom'},
{text:`She's the glue. The anchor. The light.\n\nA custom song tells her she's all three.`,link:MO,category:'mom'},
{text:`Moms don't retire. They don't take days off.\n\nThe least we can do is give them a song.`,link:MO,category:'mom'},
{text:`Every lullaby she sang you as a kid?\n\nNow it's your turn to sing one back — as a custom song.`,link:MO,category:'mom'},
{text:`She'll say "you didn't have to do this."\n\nBut her tears will say "I'm so glad you did."`,link:MO,category:'mom'},
{text:`Your mom always put herself last.\n\nA custom song puts her FIRST for once.`,link:MO,category:'mom'},
{text:`She texted "are you eating enough?" again.\n\nGive her a song that says "I'm doing great — because of you."`,link:MO,category:'mom'},
{text:`She gave you roots and wings.\n\nGive her a melody and tears of joy.`,link:MO,category:'mom'},
{text:`You can't repay everything your mom has done.\n\nBut you CAN give her something that tries — a custom song.`,link:MO,category:'mom'},
{text:`She's not just your mom. She's your first friend, your biggest cheerleader, your forever hero.\n\nGive her a song for all of it.`,link:MO,category:'mom'},
{text:`A custom song for Mom isn't just a gift.\n\nIt's an apology for every gray hair and a thank you for every sacrifice.`,link:MO,category:'mom'},
{text:`She'll frame the lyrics. Play the song at every family dinner. Show all her friends.\n\nThat's Mom with a custom song.`,link:MO,category:'mom'},
{text:`She made you who you are.\n\nThe least you can do is make her a song.`,link:MO,category:'mom'},
{text:`Your mom's fridge is full of your old drawings.\n\nGive her something new to brag about — a personalized song.`,link:MO,category:'mom'},
];

// ─── DAD (50 posts) ───────────────────────────────────────
const DA = `${S}/custom-song-for-dad`;
export const dad: Post[] = [
{text:`Dad taught you to ride a bike, throw a ball, and never give up.\n\nTime to give him something that makes HIM speechless.`,link:DA,category:'dad'},
{text:`Dads pretend they don't get emotional. A custom song proves otherwise.`,link:DA,category:'dad'},
{text:`He showed up. Every game. Every recital. Every time.\n\nShow up for him — with a song he'll treasure.`,link:DA,category:'dad'},
{text:`Your dad worked overtime so you could have everything.\n\nGive him something money can't buy — a custom song.`,link:DA,category:'dad'},
{text:`"My kids got me a custom song for Father's Day. I had to leave the room."\n\nReal dads. Real tears.`,link:DA,category:'dad'},
{text:`He didn't teach you with words. He taught you by example.\n\nA custom song teaches him how loved he is.`,link:DA,category:'dad'},
{text:`He's the quiet hero of your life.\n\nA custom song gives him the loudest standing ovation.`,link:DA,category:'dad'},
{text:`Dad jokes are his love language.\n\nBut a custom song? That's YOUR love language to him.`,link:DA,category:'dad'},
{text:`He'd give you the shirt off his back.\n\nGive him a song from your heart.`,link:DA,category:'dad'},
{text:`He pretended the tooth fairy was real. He pretended he wasn't tired.\n\nStop pretending a tie is enough. Get him a song.`,link:DA,category:'dad'},
{text:`Your dad is the reason you know what real love looks like.\n\nA custom song tells him you've been paying attention.`,link:DA,category:'dad'},
{text:`He fixed everything — the broken toys, the broken hearts, the broken moments.\n\nThis time, YOU get to fix his heart. With a song.`,link:DA,category:'dad'},
{text:`He never asked for applause.\n\nBut a standing ovation in the form of a custom song? He deserves that.`,link:DA,category:'dad'},
{text:`Your dad drove you everywhere. Picked you up at midnight. Never complained.\n\nA custom song picks HIM up. Right where it matters.`,link:DA,category:'dad'},
{text:`He's a man of few words.\n\nGood thing a custom song says everything he needs to hear.`,link:DA,category:'dad'},
{text:`Your dad probably won't tell anyone the song made him emotional.\n\nBut he'll play it every morning in the garage. That's enough.`,link:DA,category:'dad'},
{text:`He coached your team. Built your confidence. Believed in you first.\n\nBelieve in HIM back — with a custom song.`,link:DA,category:'dad'},
{text:`Dad doesn't want a fancy dinner.\n\nHe wants to know his kids turned out okay and that they love him.\n\nA song says both.`,link:DA,category:'dad'},
{text:`He carried you on his shoulders as a kid.\n\nNow carry his heart with a custom song.`,link:DA,category:'dad'},
{text:`He's tough on the outside, soft on the inside.\n\nA custom song goes straight to the soft part.`,link:DA,category:'dad'},
{text:`Your dad may not dance in public.\n\nBut play his custom song? He might.`,link:DA,category:'dad'},
{text:`He was your first hero.\n\nGive him a hero's anthem — his very own custom song.`,link:DA,category:'dad'},
{text:`Behind his "I'm fine" is a man who gives everything to his family.\n\nA custom song says "We see you, Dad. And we love you."`,link:DA,category:'dad'},
{text:`He'll call it "just a song." Then he'll play it on loop for three months.\n\nDads and custom songs — a love story.`,link:DA,category:'dad'},
{text:`Your dad has been the background music to your whole life.\n\nTime to make HIM the main track.`,link:DA,category:'dad'},
];
