import { Post, S } from './types';
const C = `${S}/create`;
const c = 'scenario';

export const scenario: Post[] = [
{text:`Imagine this:\n\nYou're at dinner. Normal Tuesday night. Nothing special.\n\nYou hand them your phone and say "listen to this song I found."\n\nThey put in their earbuds. Press play.\n\n30 seconds in, they look up at you confused.\n\n"Wait... is this... is this about US?"\n\nYou just smile.\n\nBy the chorus, they're crying. By the end, they're holding you and whispering "how did you do this?"\n\nThat's a $79 custom song. That's a random Tuesday turned into one of the best moments of your relationship.\n\nNo occasion needed. Just love.\n\n#surprisegift #customsong #lovesong #tuesdaymood #relationships #makethemcry`,link:C,category:c},

{text:`Picture this:\n\nIt's your parents' 30th wedding anniversary. The whole family is there.\n\nSomeone stands up and says "we made something for you." A song starts playing.\n\nIt mentions how they met at that diner in 1996. Their first apartment with the broken AC. Each kid being born. The vacations. The hard years. The inside jokes only the family knows.\n\nMom is done within 10 seconds — full tears. Dad is trying SO hard to hold it together and failing.\n\nThe room is silent. Then everyone is hugging.\n\nTHAT is a custom song. THAT is a family gift. THAT is the anniversary present that becomes legend.\n\n$79. Ship it.\n\n#anniversarygift #parents #familylove #customsong #30thanniversary #familygoals`,link:`${S}/custom-song-for-parents`,category:c},

{text:`The scene:\n\nGraduation party. Your kid just walked across that stage. Family is gathered.\n\nYou call everyone's attention. Hit play on a speaker.\n\nA song starts. It's about THEM. From the first day of kindergarten to today. The braces. The heartbreaks. The wins. The 2am homework sessions. The person they became.\n\nYour 22-year-old who's "too cool to cry" is absolutely sobbing.\n\nBecause they just heard their entire coming-of-age story told in 3 minutes. And they realized: someone was paying attention the whole time.\n\nBest graduation gift. $79. Not debatable.\n\n#graduation #gradgift #classof2026 #customsong #proudparent #familymoment`,link:`${S}/graduation-song-gift`,category:c},

{text:`The reveal:\n\nYou've been hiding it for weeks. The custom song arrived 5 days ago and you've been dying to show her.\n\nIt's Valentine's Day morning. You make breakfast. Set up the speaker.\n\n"I got you something different this year."\n\nShe sits down. You press play.\n\nThe first verse mentions the coffee shop where you met. Her eyes go wide. The chorus says what you've never been able to say out loud. Her hand goes to her mouth.\n\nBy the bridge — the part about building a life together — she's pulling you in. "This is the best gift anyone's ever given me."\n\nYou spent $79. She'll remember it for the rest of her life.\n\nThat's the trade.\n\n#valentinesday #customsong #lovesong #surprisegift #giftsforher #valentinesgift`,link:C,category:c},

{text:`The moment it hits different:\n\nYou order a memorial song about your grandfather. You include the details — his garden, his laugh, the way he called everyone "kiddo," the smell of his workshop.\n\nWhen the song arrives, you play it alone first.\n\n30 seconds in, you're transported. It's like he's there. The lyrics capture him so perfectly you can almost hear his voice.\n\nYou play it for your mom on his birthday. She hasn't smiled talking about him in months. But this time, through the tears, she's smiling. "That's him. That's exactly him."\n\nA memorial song doesn't bring them back. But for 3 minutes... it gets close.\n\n#grief #memorial #customsong #grandpa #inmemory #healingmusic`,link:`${S}/memorial-tribute-song`,category:c},

{text:`How it works:\n\n1️⃣ You tell us your story (5 minutes)\n— How you met. What they mean to you. The memories that matter. The feelings you want them to hear.\n\n2️⃣ We create your song (3-5 days)\n— Real music. Real lyrics. Your story set to the genre they love.\n\n3️⃣ They hear it for the first time\n— This is the moment. The tears. The "how did you do this?" The replaying it immediately. The showing everyone they know.\n\nThat's it. $79. No catching lyrics. No generic love songs. YOUR words. YOUR story. THEIR reaction.\n\nThe only question is: who in your life needs to hear their story told?\n\n#howitworks #customsong #personalizedgifts #easygifts #lovesong #giftideas`,link:C,category:c},

{text:`Real scenario that happens every week:\n\nSomeone DMs us: "I need this by Saturday. Is that possible?"\n\nUsually it's a husband who remembered his anniversary at the last second. Or a daughter who's giving a speech at her mom's birthday party.\n\nWe get it. Life is busy. That's why express delivery exists — 24 hours.\n\nBut here's the thing that surprises people: even though it's "last minute," the song doesn't feel rushed. Because we're not writing fiction. We're writing YOUR story. And your story already exists — we just put it to music.\n\nSo if you're reading this and panicking about a gift... relax.\n\nWe got you. $79 + $39 express. Ready by tomorrow.\n\n#lastminutegift #expressdelivery #customsong #giftideas #panicgifting #wegotthis`,link:C,category:c},

{text:`Late night thought:\n\nEvery couple has "their song." But usually it's a random song that happened to be playing at the right moment.\n\nWhat if "your song" was ACTUALLY your song? Written about YOUR relationship. YOUR memories. YOUR love.\n\nNot just a song you associate with each other — but a song that IS about you. That tells YOUR story. That only exists because of YOUR love.\n\nThat's what a custom song is. It doesn't borrow someone else's words. It creates yours.\n\nEvery couple deserves a song that's actually, literally, specifically THEIRS.\n\n$79.\n\n#oursong #customsong #couplesgoals #lovesong #relationships #yourlovestory`,link:C,category:c},
];
