import { Post, S } from './types';
const C = `${S}/create`;
const c = 'seasonal-emotional';

export const seasonalEmotional: Post[] = [
{text:`Father's Day is coming and I need to say something:\n\nDads don't get enough credit for the quiet stuff.\n\nThe 5am alarm so the kids have what they need. The "ask your mother" that's really just "I don't want to be the bad guy." The pride they carry silently when you accomplish something. The worry they never show.\n\nMost dads will say they don't want anything for Father's Day. They're lying. They want to know it mattered. That you noticed.\n\nA custom song about the specific things YOUR dad did? The coaching. The driving. The working. The showing up.\n\nThat's the gift that finally says: "I saw everything you did for us, Dad. Thank you."\n\n#fathersday #dadsday #giftfordad #customsong #dadlife #fatherslove`,link:`${S}/custom-song-for-dad`,category:c},

{text:`Mother's Day thought:\n\nYour mom didn't become "Mom" by accident. She chose it. Every day. Through the sleepless nights, the thankless mornings, the moments where she put herself last so you could come first.\n\nAnd what do we usually give her? A brunch reservation and a candle.\n\nThis year, give her something that makes her feel like you actually understand what she gave up. What she endured. What she built.\n\nA custom song about HER — not just "thanks Mom" but the specific memories, the moments she doesn't think you remember, the sacrifice you DO see — that's the gift she deserves.\n\nShe gave you everything. Give her 3 minutes that prove you know it.\n\n#mothersday #momlife #giftformom #customsong #momappreciation #motherlove`,link:`${S}/custom-song-for-mom`,category:c},

{text:`Wedding season is here. And if you're going to a wedding this summer, can we talk about gifts for a second?\n\nThe couple registered for a KitchenAid mixer. They also registered for towels. And a cutting board.\n\nThose gifts are fine. They're useful. They'll use them.\n\nBut they won't CRY opening them.\n\nYou know what makes a couple cry at their own wedding? A custom song about their love story, played during the reception. Or given as a gift they discover on the honeymoon.\n\nYou'll be the guest they talk about for 30 years. "Remember that person who gave us our SONG?"\n\nBe that person.\n\n#weddingseason #weddinggift #customsong #brideandgroom #weddingideas`,link:`${S}/custom-song-as-wedding-gift`,category:c},

{text:`Christmas is months away but I'm planting this seed NOW:\n\nThe best Christmas gift I've ever seen given wasn't under the tree. It was played on a speaker while the whole family sat together.\n\nA custom song about the family. The traditions. The grandparents. The inside jokes. The Christmases past.\n\nEvery person in that room felt it. Grandma cried. The teenagers put their phones down. Dad pretended he had something in his eye.\n\nYou want to WIN Christmas this year? Start thinking about it now. A custom family song takes 5 days to make. Don't wait until December 20th.\n\n$79 for a gift the whole family shares forever.\n\n#christmas #christmasgift #familygift #customsong #holidaygift #earlybird`,link:`${S}/christmas-gift-song`,category:c},

{text:`Graduation gift idea that actually means something:\n\nDon't just hand them a check in a card. (They'll spend it on DoorDash and forget about it.)\n\nGive them a song about their journey. The late nights studying. The friendships they built. The person they became over 4 years. The proud parents watching from the stands.\n\nA custom graduation song captures WHO THEY WERE at this specific moment in their life. In 10 years, when they're deep in their career and life looks completely different, they'll play it and remember exactly who they were when everything was just beginning.\n\nThat's the gift that grows in value over time.\n\n#graduation #gradgift #classof2026 #customsong #collegegrad #gradparty`,link:`${S}/graduation-song-gift`,category:c},

{text:`Birthday coming up for someone you love? Here's the gift that beats everything else:\n\nNot a party. Not a trip. Not a piece of jewelry.\n\nA song that's literally about them.\n\nTheir personality. Their journey this year. The things that make them THEM. Set to their favorite genre of music.\n\nImagine opening Spotify and there's a song with YOUR name as the title. You press play and every lyric is about YOUR life, YOUR relationships, YOUR moments.\n\nThat's not a gift. That's a core memory.\n\nWorks for any age. Any budget ($79). Any relationship. The only requirement: you love them enough to tell their story.\n\n#birthdaygift #birthdayideas #customsong #personalizedgifts #birthdayparty`,link:`${S}/birthday-song-gift`,category:c},

{text:`Valentine's Day truth bomb:\n\nRoses die in a week. Chocolate is gone in a day. Fancy dinner? Forgotten by March.\n\nBut a custom love song about YOUR relationship? They'll listen to it in the car tomorrow. Next month. On your anniversary. In 10 years.\n\nIt's the only Valentine's gift that actually LASTS.\n\nAnd here's the thing — it doesn't have to be cheesy. It can be funny. Upbeat. Acoustic. R&B. Country. Whatever fits YOUR relationship.\n\nBecause your love isn't generic. Your gift shouldn't be either.\n\nCustom songs starting at $79. Your love story deserves its own soundtrack.\n\n#valentinesday #valentinesgift #lovesong #customsong #galentines #relationships`,link:C,category:c},

{text:`Anniversary gift ranked by how hard they make your partner cry (good tears):\n\n5. Jewelry — nice, expected, she'll wear it\n4. Trip — great memories, over in a weekend\n3. Love letter — emotional, personal, read once or twice\n2. Surprise party — amazing moment, fades in memory\n1. Custom song about your relationship — played DAILY, cried to repeatedly, shown to every friend, becomes "your song" forever\n\nThe hierarchy is clear.\n\n$79. 3-5 day delivery. Express available.\n\nLink in bio.\n\n#anniversary #anniversarygift #customsong #couplesgoals #romanticgift #wifegift`,link:C,category:c},
];
