import { Post, S } from './types';
const C = `${S}/create`;
const c = 'stories';

export const stories: Post[] = [
{text:`My dad never says "I love you."\n\nHe says it in other ways — waking up early to drive me to practice, working overtime so I could go to camp, sitting in the driveway at 2am waiting for me to get home safe.\n\nFor his 60th birthday, I had a song made about all the things he did that I noticed. All the silent ways he loved us.\n\nWhen he heard it, he just sat there. Then his chin started shaking. Then he pulled me in and said "you noticed all that?"\n\nYeah, Dad. I noticed everything.\n\nIf you have a dad like this — the quiet ones who show love through action — a custom song lets him know you've been paying attention all along.\n\n#fathersday #dadlove #customsong #giftfordad #personalgift`,link:`${S}/custom-song-for-dad`,category:c},

{text:`She keeps everything.\n\nThe movie tickets from your first date. The napkin you wrote "I love you" on at dinner. The voicemail she saved from three years ago.\n\nShe doesn't need another necklace. She needs you to prove that you've been paying just as much attention as she has.\n\nA custom song filled with YOUR details — the first time you saw her, what she was wearing, what you said that made her laugh — that's the gift that finally matches her love language.\n\nShe notices everything. Make her feel noticed back.\n\n#giftsforher #lovesong #customsong #romanticgift #anniversary`,link:`${S}/custom-song-for-wife`,category:c},

{text:`True story: A guy ordered a custom song for his wife's birthday. Nothing crazy — just 3 minutes about their life together.\n\nHe mentioned the laundromat where they met. The burnt pancakes from their first morning together. Their daughter's first word. The time they slow danced in the kitchen at midnight.\n\nWhen she heard it, she played it three times in a row without saying a word. Then she looked at him and said: "How did they get our whole life into one song?"\n\nThat's what happens when you give someone a gift made entirely from your memories. It doesn't just make them happy. It makes them feel KNOWN.\n\n#customsong #personalgift #giftsthatmatter #anniversarygift #lovegift`,link:C,category:c},

{text:`Here's the thing about grief that nobody tells you:\n\nYou don't miss the big moments as much as the small ones.\n\nYou miss the way they hummed while cooking. The sound of their keys in the door. The texts that just said "thinking of you."\n\nA memorial song doesn't try to fix the grief. It gives you somewhere to PUT it. A 3-minute container where it's safe to remember, to cry, to smile at the memories.\n\nSome people listen to theirs every day. Some only on birthdays and anniversaries. Either way — it keeps the person close when everything else fades.\n\nIf you've lost someone and wish you could hear their story told one more time — we can help with that.\n\n#grief #memorial #customsong #inmemory #lovedones #loss`,link:`${S}/memorial-tribute-song`,category:c},

{text:`When I was little, my mom used to sing me the same song every night before bed. Just a made-up melody with my name in it.\n\nI'm 34 now and I can still hear it perfectly.\n\nThat's what music does — it embeds itself into your memory deeper than any physical gift ever could. A song isn't something you put on a shelf. It becomes part of you.\n\nIf there's someone you love and you want to give them something they'll carry with them forever — not in their closet, but in their heart — a custom song does that.\n\n$79. 3 minutes. A lifetime of memories.\n\n#customsong #musicismemory #personalgifts #meaningfulgifts #giftsforher`,link:C,category:c},

{text:`Nobody told me the hardest part of a proposal isn't the ring.\n\nIt's figuring out what to SAY.\n\nYou've rehearsed it 100 times in the shower. You've written notes on your phone at 2am. You know exactly how you feel — but when you try to put it into words, nothing feels big enough.\n\nThat's why some people let a song say it for them.\n\nImagine this: You're at your spot. The sun is setting. You press play on a speaker. And a song starts — YOUR song — about how you met, how you knew, and why it's always been her.\n\nBy the time you're on one knee, she already knows.\n\n#proposal #engagementring #customsong #proposalsong #shesaidyes #engaged`,link:`${S}/custom-song-for-proposal`,category:c},

{text:`My grandmother is 87 and she's starting to forget things.\n\nShe forgets what day it is. She forgets if she ate lunch. But when you play her favorite song from 1962, she lights up like she's 20 again.\n\nMusic is the last thing to go. It's stored in a different part of the brain than regular memories. That's why a custom song about someone's life — their story, their family, their moments — becomes one of the most powerful things you can give them.\n\nNot because it's a nice gift. But because even when everything else fades… the song stays.\n\nIf you have a grandparent, a parent, or someone whose memory is fading — give them their story in music while they can still feel every word.\n\n#dementia #alzheimers #musictherapy #memorialsong #grandparents #familygift`,link:`${S}/custom-song-for-grandparents`,category:c},

{text:`I asked a group of people: "What's the best gift you've ever received?"\n\nNot a single person said a physical item.\n\nEvery answer was the same energy:\n"Something that showed they really knew me."\n"A surprise that proved they'd been paying attention."\n"Something I'd never think to ask for myself."\n\nA custom song checks every box. It shows you listened. It surprises them with details only you would know. And nobody ever thinks to ask for their own song.\n\nThat's what makes it hit so hard — it's the gift they never knew they needed but will replay for years.\n\n#gifting #personalizedgifts #customsong #meaningfulgifts #bestgiftever`,link:C,category:c},
];
